<a href="https://colab.research.google.com/github/MikeDaBossss/Placestolive/blob/master/rent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import files
upload = files.upload()#'/content/drive/My Drive/jobs_indeed.csv'

In [0]:
upload

{}

In [0]:
import pandas as pd
countyrent = pd.read_excel('/Median Rent By county.xls')

FileNotFoundError: ignored

In [0]:
countyrent.to_excel('/content/drive/My Drive/MedianRentCounty.xls')

In [0]:
countyrent

        fips2010  rent50_0  rent50_1  ...  Unnamed: 18  Unnamed: 19  Unnamed: 20
0     7200999999       319       337  ...          NaN           AR          NaN
1     7201999999       319       337  ...          NaN           PR          NaN
2     7203999999       319       337  ...          NaN           TN          NaN
3     7209599999       319       337  ...          NaN           MO          NaN
4     7210799999       319       337  ...          NaN           WV          NaN
...          ...       ...       ...  ...          ...          ...          ...
4765  2301347962       749       754  ...          NaN          NaN          NaN
4766  2301541280       751       797  ...          NaN          NaN          NaN
4767  3300942820       760       885  ...          NaN          NaN          NaN
4768  2300742765       585       625  ...          NaN          NaN          NaN
4769  2302911755       653       657  ...          NaN          NaN          NaN

[4770 rows x 21 columns]

In [0]:
import folium
from folium import plugins
m = folium.Map([42, -80.6298], zoom_start=11)
m.add_children(plugins.HeatMap(stationArr, radius=15))

NameError: ignored

In [0]:
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="specify_your_app_name_here")
location = geolocator.geocode("Aibonito Municipio")
print(location.address)

Aibonito, Puerto Rico, 00705, United States of America

In [0]:
countyrent['cntyname']

0           Aibonito Municipio
1       Barranquitas Municipio
2             Ciales Municipio
3            Maunabo Municipio
4           Orocovis Municipio
                 ...
4765               Knox County
4766            Lincoln County
4767            Grafton County
4768           Franklin County
4769         Washington County
Name: cntyname, Length: 4770, dtype: object

In [0]:
lat = []
lon = []

for name in countyrent['cntyname'] : 
  print(name)
  try:
    lat.append(geolocator.geocode(name).latitude)
    lon.append(geolocator.geocode(name).longitude)
  except:
    lat.append(0)
    lon.append(0)
    print('error')
countyrent['lat'] = lat
countyrent['lon'] = lon

Streaming output truncated to the last 5000 lines.
error
Humboldt County
error
Neosho County
error
Telfair County
error
Rutland County
error
Smith County
error
Benton County
error
Fairfield County
error
Mercer County
error
Pike County
error
Gogebic County
error
Dixie County
error
Radford city
error
Torrance County
error
Cumberland County
error
Lewis County
error
Iowa County
error
Knott County
error
Clark County
error
Norfolk County
error
Richland County
error
Bristol County
error
Floyd County
error
Osage County
error
Essex County
error
Rabun County
error
Jackson Parish
error
Idaho County
error
Alleghany County
error
Brooks County
error
Kanabec County
error
Richland County
error
Vermillion County
error
Park County
error
Aitkin County
error
Worcester County
error
Ashland County
error
Newport County
error
Baker County
error
Hill County
error
Clay County
error
New London County
error
Redwood County
error
Hampshire County
error
Greene County
error
Bamberg County
error
Plymouth County
error
Casey County
error
Providence County
error
Belknap County
error
Tipton County
error
King William County
error
Page County
error
Washburn County
error
Dickenson County
error
Arenac County
error
Carbon County
error
Bristol County
error
Washington County
error
Bristol County
error
Harrison County
error
Gulf County
error
Lawrence County
error
Nottoway County
error
Marshall County
error
Hampden County
error
Newport County
error
San Juan County
error
Bennington County
error
Hale County
error
Otoe County
error
Hartford County
error
Renville County
error
Kennebec County
error
Hampden County
error
Madison County
error
Worcester County
error
Madison County
error
Hamilton County
error
Dent County
error
Park County
error
Roseau County
error
West Feliciana Parish
error
Moniteau County
error
Tolland County
error
Mitchell County
error
Macon County
error
Kossuth County
error
Union County
error
Grayson County
error
Bristol County
error
Pecos County
error
Las Animas County
error
Gooding County
error
Burnett County
error
Alamosa County
error
Walthall County
error
Rockingham County
error
Massac County
error
Henry County
error
Windham County
error
Marquette County
error
Carroll County
error
Tallahatchie County
error
Gunnison County
error
Winn Parish
error
Floyd County
error
Brown County
error
Sibley County
error
Gasconade County
error
Nolan County
error
Choctaw County
error
Livingston County
error
Calhoun County
error
Bourbon County
error
Hillsborough County
error
Jeff Davis County
error
Mills County
error
Plymouth County
error
Morgan County
error
Tolland County
error
New London County
error
Kingfisher County
error
Craig County
error
Nelson County
error
Bayfield County
error
Union County
error
Appomattox County
error
Cleburne County
error
Calhoun County
error
Harrison County
error
Roane County
error
Middlesex County
error
Dooly County
error
Oglethorpe County
error
Middlesex County
error
La Salle Parish
error
Pendleton County
error
Butler County
error
Missaukee County
error
Moultrie County
error
Fulton County
error
Grand County
error
Karnes County
error
Hamilton County
error
Chowan County
error
Andrews County
error
Jefferson County
error
Rusk County
error
San Juan County
error
Macon County
error
Washington County
error
Estill County
error
Mason County
error
White County
error
Hampshire County
error
Noble County
error
Monroe County
error
Strafford County
error
Calhoun County
error
Norfolk County
error
Screven County
error
Crockett County
error
Trinity County
error
Lamar County
error
Faribault County
error
Braxton County
error
Plymouth County
error
Long County
error
Newton County
error
New Haven County
error
Greene County
error
Union County
error
O'Brien County
error
Mississippi County
error
Bienville Parish
error
Fleming County
error
Trigg County
error
McIntosh County
error
Allamakee County
error
Rockingham County
error
Manassas Park city
error
Newton County
error
Hampden County
error
Barnstable County
error
Mono County
error
Saline County
error
Larue County
error
Atoka County
error
Price County
error
Worcester County
error
Lincoln County
error
Sequatchie County
error
Ripley County
error
Ford County
error
Jackson County
error
Crawford County
error
Williamsburg city
error
Clarke County
error
Hardy County
error
Zapata County
error
Barnstable County
error
Middlesex County
error
Hughes County
error
Cedar County
error
Swain County
error
Lamb County
error
Comanche County
error
Cass County
error
New Haven County
error
Rolette County
error
Clay County
error
Pennington County
error
Summers County
error
Morgan County
error
Crenshaw County
error
Jasper County
error
Greene County
error
Fairfield County
error
Plymouth County
error
Osage County
error
Breathitt County
error
Lewis County
error
Clay County
error
Choctaw County
error
Wadena County
error
Dawson County
error
Converse County
error
Martinsville city
error
Clay County
error
Cannon County
error
Moffat County
error
Plymouth County
error
Howard County
error
Essex County
error
Trinity County
error
Reeves County
error
Sumter County
error
Colfax County
error
Bristol County
error
Worcester County
error
Berkshire County
error
Grundy County
error
Izard County
error
Douglas County
error
York County
error
Madison County
error
Cass County
error
Webster County
error
Worcester County
error
Rockingham County
error
Kodiak Island Borough
error
Buffalo County
error
Oglala Lakota County
error
Middlesex County
error
Callahan County
error
Wilbarger County
error
Wayne County
error
Monroe County
error
Jackson County
error
Murray County
error
Ketchikan Gateway Borough
error
Jackson County
error
Worcester County
error
Perquimans County
error
Merrimack County
error
Vinton County
error
Pulaski County
error
Glacier County
error
Bristol County
error
Presque Isle County
error
Allen County
error
Sullivan County
error
Magoffin County
error
Stewart County
error
Middlesex County
error
Koochiching County
error
Madison County
error
Worcester County
error
Middlesex County
error
Goshen County
error
Fremont County
error
Wright County
error
Conecuh County
error
Washington County
error
Essex County
error
Little River County
error
Grafton County
error
Kent County
error
Pamlico County
error
Amite County
error
Bleckley County
error
Desha County
error
Pend Oreille County
error
Middlesex County
error
Caldwell County
error
Worcester County
error
Middlesex County
error
Morris County
error
Martin County
error
Lawrence County
error
Lunenburg County
error
New Haven County
error
Hillsborough County
error
DeKalb County
error
Appanoose County
error
Glades County
error
Bledsoe County
error
Big Horn County
error
Red River County
error
Pike County
error
Franklin County
error
Haskell County
error
Blackford County
error
Shoshone County
error
Linn County
error
Norfolk County
error
Menard County
error
Butler County
error
Amelia County
error
New Haven County
error
Yalobusha County
error
Marion County
error
Terry County
error
Marshall County
error
Crawford County
error
Plymouth County
error
Powell County
error
Charlotte County
error
Johnson County
error
Prowers County
error
Union County
error
York County
error
Millard County
error
Hartford County
error
Jefferson Davis County
error
Todd County
error
Grundy County
error
Chippewa County
error
Chickasaw County
error
Tolland County
error
Barton County
error
Camp County
error
Stone County
error
Northampton County
error
Bollinger County
error
Falls Church city
error
Northumberland County
error
Perry County
error
Fulton County
error
Greensville County
error
Litchfield County
error
Barnstable County
error
Montgomery County
error
Madison County
error
Gates County
error
Okfuskee County
error
Charlton County
error
Shelby County
error
Lewis County
error
Edmonson County
error
Poquoson city
error
Hampden County
error
Madison Parish
error
Tolland County
error
Sussex County
error
Archuleta County
error
Cherokee County
error
Windham County
error
Norfolk County
error
Pulaski County
error
Sierra County
error
Rio Grande County
error
Providence County
error
New London County
error
Wabash County
error
Blaine County
error
Grant County
error
Heard County
error
Iron County
error
Chicot County
error
Duval County
error
Strafford County
error
Decatur County
error
Meigs County
error
Washington County
error
Custer County
error
Worcester County
error
Cottonwood County
error
Zavala County
error
Wilcox County
error
Big Horn County
error
Jackson County
error
Washita County
error
Bristol County
error
West Carroll Parish
error
Essex County
error
Bath County
error
Fergus County
error
Worcester County
error
Lyon County
error
Pushmataha County
error
Noble County
error
Franklin County
error
Noxubee County
error
Lake County
error
Coosa County
error
Live Oak County
error
Owyhee County
error
Plymouth County
error
Bradley County
error
Middlesex County
error
Ramsey County
error
Tolland County
error
Sanders County
error
Jefferson County
error
Lancaster County
error
Worcester County
error
Louisa County
error
Hancock County
error
Leslie County
error
Box Butte County
error
Lowndes County
error
Middlesex County
error
Pike County
error
Hartford County
error
Chattahoochee County
error
Middlesex County
error
Grafton County
error
Green County
error
Litchfield County
error
Scott County
error
Norfolk County
error
Watonwan County
error
St. Helena Parish
error
Hillsborough County
error
Lake County
error
Cumberland County
error
Morrow County
error
Hartford County
error
Alleghany County
error
Latimer County
error
Essex County
error
Walsh County
error
Mackinac County
error
Bacon County
error
Barnes County
error
Skamania County
error
Red Willow County
error
Cumberland County
error
Early County
error
Evans County
error
Candler County
error
Pope County
error
Emery County
error
Boundary County
error
Worcester County
error
Monroe County
error
Middlesex County
error
Johnston County
error
Norfolk County
error
Guthrie County
error
Alcona County
error
Custer County
error
Montgomery County
error
Bullock County
error
Rains County
error
Oregon County
error
Winnebago County
error
Lake County
error
Owen County
error
Sabine County
error
Carroll County
error
York County
error
Norfolk County
error
Tunica County
error
Mitchell County
error
Clay County
error
Montgomery County
error
Crawford County
error
Franklin County
error
Ward County
error
Middlesex County
error
Iron County
error
Switzerland County
error
Bristol County
error
Franklin County
error
Plymouth County
error
Carroll County
error
Wilkes County
error
Perry County
error
Clay County
error
Lincoln County
error
Marion County
error
Nowata County
error
Colfax County
error
Keokuk County
error
Plymouth County
error
Runnels County
error
Blanco County
error
Towns County
error
Kemper County
error
Ritchie County
error
Perry County
error
Yellow Medicine County
error
Holt County
error
Roosevelt County
error
Lee County
error
Allendale County
error
Catahoula Parish
error
Penobscot County
error
Chittenden County
error
Sac County
error
Martin County
error
Providence County
error
Bristol County
error
Emmet County
error
Worcester County
error
Plymouth County
error
Hartford County
error
Clinton County
error
Parmer County
error
Jackson County
error
Grundy County
error
Webster County
error
Sublette County
error
Juab County
error
Middlesex County
error
McCormick County
error
Ochiltree County
error
Lewis County
error
Plymouth County
error
Washington County
error
Fairfield County
error
Nemaha County
error
Nantucket County
error
Teton County
error
Ralls County
error
Jones County
error
Roberts County
error
Howard County
error
Rockingham County
error
Caldwell Parish
error
Marshall County
error
Carroll County
error
Butte County
error
Middlesex County
error
Metcalfe County
error
Worcester County
error
Rice County
error
Lanier County
error
Carbon County
error
Cumberland County
error
Coos County
error
Yuma County
error
White Pine County
error
Cheyenne County
error
Dimmit County
error
Brown County
error
Johnson County
error
Camden County
error
Litchfield County
error
Windsor County
error
Wilkinson County
error
Cumberland County
error
Hampshire County
error
Valley County
error
Barnstable County
error
Humboldt County
error
St. Clair County
error
Swift County
error
Worcester County
error
Montmorency County
error
Richland County
error
Providence County
error
Stevens County
error
Ozark County
error
Jasper County
error
Aroostook County
error
Rock County
error
Modoc County
error
Tolland County
error
Calhoun County
error
Pratt County
error
Linn County
error
Valdez-Cordova Census Area
error
Stephens County
error
Hickory County
error
Todd County
error
Claiborne County
error
Alger County
error
Pipestone County
error
Wayne County
error
York County
error
Windham County
error
Howard County
error
Wilkinson County
error
Irwin County
error
Cloud County
error
McLean County
error
Livingston County
error
Middlesex County
error
Hampden County
error
Nome Census Area
error
York County
error
Montgomery County
error
Penobscot County
error
Morgan County
error
Windham County
error
Kiowa County
error
Marshall County
error
North Slope Borough
error
Hancock County
error
Caldwell County
error
Love County
error
Palo Alto County
error
Wilson County
error
New Haven County
error
Mitchell County
error
Clay County
error
Humphreys County
error
Windsor County
error
Greene County
error
Crittenden County
error
Terrell County
error
Forest County
error
Hartford County
error
Deer Lodge County
error
Carroll County
error
Clarke County
error
Benewah County
error
Worcester County
error
Wilcox County
error
Richmond County
error
Beaverhead County
error
Monona County
error
Rosebud County
error
Brewster County
error
Grand County
error
Tyler County
error
Phelps County
error
Dawes County
error
Maries County
error
Fairfield County
error
Webster County
error
Cuming County
error
Charles Mix County
error
Middlesex County
error
Hamilton County
error
Montgomery County
error
Stillwater County
error
Red River Parish
error
Clear Creek County
error
Archer County
error
Washington County
error
Greene County
error
Jack County
error
Quay County
error
Worcester County
error
Twiggs County
error
Cumberland County
error
Androscoggin County
error
Nevada County
error
New Haven County
error
Essex County
error
Mathews County
error
Dawson County
error
Worcester County
error
McLean County
error
Harrison County
error
Rockingham County
error
Turner County
error
Middlesex County
error
Middlesex County
error
Taylor County
error
Lucas County
error
Coleman County
error
Sitka City and Borough
error
Woods County
error
Lafayette County
error
Bristol County
error
San Augustine County
error
Graham County
error
Baraga County
error
Benton County
error
Cedar County
error
Monroe County
error
Trimble County
error
Hillsborough County
error
Sagadahoc County
error
Clearwater County
error
Davis County
error
Marion County
error
Benton County
error
Seminole County
error
Murray County
error
Pocahontas County
error
Prairie County
error
Knox County
error
Chittenden County
error
Clearwater County
error
Gilmer County
error
Rockingham County
error
Cleveland County
error
Platte County
error
Oscoda County
error
York County
error
Coffey County
error
Gallatin County
error
Somerset County
error
Franklin city
error
Strafford County
error
Johnson County
error
Hancock County
error
Hampden County
error
Choctaw County
error
Clay County
error
Washakie County
error
Rockingham County
error
Hamilton County
error
Sagadahoc County
error
Warren County
error
Addison County
error
Somervell County
error
Bracken County
error
Schoolcraft County
error
Berkshire County
error
Merrimack County
error
Worcester County
error
Litchfield County
error
Decatur County
error
Hamilton County
error
Shannon County
error
Greenlee County
error
Franklin County
error
Daviess County
error
Houston County
error
Mercer County
error
Butler County
error
Atkinson County
error
Keith County
error
Liberty County
error
Richardson County
error
Cumberland County
error
Turner County
error
Middlesex County
error
Jenkins County
error
Newton County
error
Lyon County
error
McCulloch County
error
Essex County
error
Hillsborough County
error
Kit Carson County
error
Norfolk County
error
Conejos County
error
Ballard County
error
Alexander County
error
Quitman County
error
Custer County
error
Windham County
error
Doddridge County
error
Searcy County
error
Aroostook County
error
Washington County
error
Essex County
error
Monroe County
error
Traill County
error
Franklin County
error
Dallas County
error
Anderson County
error
Castro County
error
Worcester County
error
York County
error
Worcester County
error
Lincoln County
error
Tillman County
error
Worcester County
error
Monroe County
error
Essex County
error
Windham County
error
Doniphan County
error
Lemhi County
error
Washington County
error
Perry County
error
Thomas County
error
Lake County
error
Norfolk County
error
Lee County
error
Litchfield County
error
Dade County
error
Yoakum County
error
Cumberland County
error
Trousdale County
error
Clay County
error
Kingman County
error
Washington County
error
Swisher County
error
Elliott County
error
Merrick County
error
Penobscot County
error
Franklin County
error
Lake County
error
Chariton County
error
Grant County
error
Washington County
error
Presidio County
error
Power County
error
Worcester County
error
Kennebec County
error
Essex County
error
Cumberland County
error
Franklin County
error
East Carroll Parish
error
Berkshire County
error
Hancock County
error
Jefferson County
error
Randolph County
error
Forest County
error
Washington County
error
Pendleton County
error
York County
error
Madison County
error
Hillsborough County
error
Adair County
error
Mountrail County
error
Worcester County
error
Lafayette County
error
Calhoun County
error
Rockingham County
error
Pleasants County
error
Caledonia County
error
New London County
error
Worth County
error
New Haven County
error
Van Buren County
error
Ferry County
error
Jefferson County
error
Schuyler County
error
Worcester County
error
Norfolk County
error
Major County
error
Northwest Arctic Borough
error
Merrimack County
error
Plymouth County
error
Union County
error
Fairfield County
error
Pepin County
error
Kusilvak Census Area
error
Grant County
error
Fremont County
error
Middlesex County
error
Harney County
error
Wheeler County
error
Pembina County
error
Middlesex County
error
Refugio County
error
Rappahannock County
error
Valley County
error
San Miguel County
error
Grant County
error
Belknap County
error
Wolfe County
error
Hutchinson County
error
Henderson County
error
Pocahontas County
error
Lake County
error
New London County
error
Knox County
error
Worcester County
error
Chittenden County
error
Pierce County
error
Woodruff County
error
Lac qui Parle County
error
Penobscot County
error
Charles City County
error
Rockingham County
error
Nemaha County
error
York County
error
Cheshire County
error
Brooks County
error
York County
error
Cumberland County
error
Middlesex County
error
Goliad County
error
Weston County
error
Bailey County
error
Chittenden County
error
Tucker County
error
Clark County
error
Nicholas County
error
Belknap County
error
Kane County
error
Merrimack County
error
Winkler County
error
Berkshire County
error
Fall River County
error
Ida County
error
Bristol County
error
Crook County
error
Bon Homme County
error
Surry County
error
Wabaunsee County
error
Galax city
error
Lexington city
error
Childress County
error
Southeast Fairbanks Census Area
error
Boise County
error
Powell County
error
Wallowa County
error
Grafton County
error
Pawnee County
error
Russell County
error
Litchfield County
error
Caribou County
error
Essex County
error
King and Queen County
error
Thurston County
error
Middlesex County
error
Brown County
error
Franklin County
error
Plymouth County
error
La Salle County
error
Treutlen County
error
Talbot County
error
Burt County
error
Cumberland County
error
Norman County
error
Cameron Parish
error
Bland County
error
Hancock County
error
Fulton County
error
Clinch County
error
Strafford County
error
Ontonagon County
error
Berkshire County
error
Pershing County
error

ValueError: ignored

In [0]:
#this api did not work even though it has worked in the past for me.

In [0]:
from geopy.geocoders import Pelias
geolocat = Pelias(timeout=.1)
location = geolocator.geocode("Aibonito Municipio")
print(location.address)

TypeError: ignored

In [0]:
#other things that would be important to make the rent relative is the income that a person would be making. Let me download the data for different jobs in different locations
from google.colab import files
upload = files.upload()#'/content/drive/My Drive/jobs_indeed.csv'

Saving state_M2018_dl.xlsx to state_M2018_dl.xlsx

In [0]:
import pandas as pd
countyrent = pd.read_excel('state_M2018_dl.xlsx')
countyrent.to_excel('/content/drive/My Drive/JobIncomeperState.xlsx')

In [0]:
import pandas as pd
countyrent= pd.read_excel('/content/drive/My Drive/JobIncomeperState.xlsx')

In [2]:
countyrent

       Unnamed: 0  AREA  ST           STATE  ... A_PCT75 A_PCT90 ANNUAL HOURLY
0               0     1  AL         Alabama  ...   53310   79630    NaN    NaN
1               1     1  AL         Alabama  ...  132860  187330    NaN    NaN
2               2     1  AL         Alabama  ...       #       #    NaN    NaN
3               3     1  AL         Alabama  ...  147250       #    NaN    NaN
4               4     1  AL         Alabama  ...   32290   63390    1.0    NaN
...           ...   ...  ..             ...  ...     ...     ...    ...    ...
36892       36892    78  VI  Virgin Islands  ...   27330   30560    NaN    NaN
36893       36893    78  VI  Virgin Islands  ...   30590   44290    NaN    NaN
36894       36894    78  VI  Virgin Islands  ...   35980   41290    NaN    NaN
36895       36895    78  VI  Virgin Islands  ...   33640   41090    NaN    NaN
36896       36896    78  VI  Virgin Islands  ...   21070   24270    NaN    NaN

[36897 rows x 26 columns]

In [3]:
countyrent[countyrent['OCC_TITLE'].str.contains('Analyst')]['OCC_TITLE'].unique()

array(['Management Analysts',
       'Market Research Analysts and Marketing Specialists',
       'Budget Analysts', 'Credit Analysts', 'Financial Analysts',
       'Computer Systems Analysts', 'Information Security Analysts',
       'Operations Research Analysts', 'Broadcast News Analysts'],
      dtype=object)

In [4]:
#Budget Analyst is what I could do an analysis on 
countyrent[countyrent['OCC_TITLE'].str.contains('Budget Analyst')].sort_values(by='A_MEDIAN',ascending=False)

       Unnamed: 0  AREA  ST  ... A_PCT90 ANNUAL HOURLY
5592         5592    11  DC  ...  126060    NaN    NaN
13972       13972    24  MD  ...  124390    NaN    NaN
32451       32451    51  VA  ...  126070    NaN    NaN
2790         2790     6  CA  ...  133020    NaN    NaN
14730       14730    25  MA  ...  122010    NaN    NaN
4358         4358     9  CT  ...  109320    NaN    NaN
52             52     1  AL  ...  116710    NaN    NaN
21103       21103    34  NJ  ...  123710    NaN    NaN
27758       27758    44  RI  ...  117470    NaN    NaN
3603         3603     8  CO  ...  112640    NaN    NaN
7670         7670    15  HI  ...  103310    NaN    NaN
15483       15483    26  MI  ...  104130    NaN    NaN
788           788     2  AK  ...  105850    NaN    NaN
16260       16260    27  MN  ...  110080    NaN    NaN
22521       22521    36  NY  ...  110570    NaN    NaN
31186       31186    49  UT  ...  101780    NaN    NaN
20447       20447    33  NH  ...  100590    NaN    NaN
26208       26208    41  OR  ...   98120    NaN    NaN
21863       21863    35  NM  ...  107040    NaN    NaN
30378       30378    48  TX  ...  116550    NaN    NaN
33205       33205    53  WA  ...  103450    NaN    NaN
8914         8914    17  IL  ...  105340    NaN    NaN
10469       10469    19  IA  ...  104950    NaN    NaN
24684       24684    39  OH  ...  104230    NaN    NaN
13342       13342    23  ME  ...  104240    NaN    NaN
34635       34635    55  WI  ...   98300    NaN    NaN
26966       26966    42  PA  ...  102150    NaN    NaN
31893       31893    50  VT  ...   90490    NaN    NaN
5047         5047    10  DE  ...   97600    NaN    NaN
25475       25475    40  OK  ...   99140    NaN    NaN
6121         6121    12  FL  ...  103260    NaN    NaN
23315       23315    37  NC  ...  101280    NaN    NaN
1350         1350     4  AZ  ...  100420    NaN    NaN
29608       29608    47  TN  ...  101840    NaN    NaN
9698         9698    18  IN  ...   99490    NaN    NaN
6916         6916    13  GA  ...  102520    NaN    NaN
28329       28329    45  SC  ...   95390    NaN    NaN
19767       19767    32  NV  ...   96910    NaN    NaN
24068       24068    38  ND  ...   93130    NaN    NaN
35376       35376    56  WY  ...   95090    NaN    NaN
11185       11185    20  KS  ...   93610    NaN    NaN
17693       17693    29  MO  ...  100060    NaN    NaN
33967       33967    54  WV  ...  100380    NaN    NaN
12617       12617    22  LA  ...   95990    NaN    NaN
8266         8266    16  ID  ...   90160    NaN    NaN
17008       17008    28  MS  ...   83780    NaN    NaN
18450       18450    30  MT  ...   79600    NaN    NaN
29033       29033    46  SD  ...   85300    NaN    NaN
35909       35909    66  GU  ...   76880    NaN    NaN
19089       19089    31  NE  ...   95370    NaN    NaN
11887       11887    21  KY  ...   83500    NaN    NaN
36746       36746    78  VI  ...   70600    NaN    NaN
2098         2098     5  AR  ...   78470    NaN    NaN
36181       36181    72  PR  ...   69000    NaN    NaN

[54 rows x 26 columns]

In [5]:
countyrent[countyrent['LOC_Q'].str.isalnum() == False]

       Unnamed: 0  AREA  ST           STATE  ... A_PCT75 A_PCT90 ANNUAL HOURLY
64             64     1  AL         Alabama  ...  157660       #    NaN    NaN
118           118     1  AL         Alabama  ...   70130  102130    NaN    NaN
191           191     1  AL         Alabama  ...   95320  114230    1.0    NaN
211           211     1  AL         Alabama  ...   50600   60080    1.0    NaN
215           215     1  AL         Alabama  ...   57860   61820    1.0    NaN
...           ...   ...  ..             ...  ...     ...     ...    ...    ...
36869       36869    78  VI  Virgin Islands  ...   47700   52420    NaN    NaN
36870       36870    78  VI  Virgin Islands  ...   35190   38260    NaN    NaN
36877       36877    78  VI  Virgin Islands  ...   67790   77360    NaN    NaN
36893       36893    78  VI  Virgin Islands  ...   30590   44290    NaN    NaN
36895       36895    78  VI  Virgin Islands  ...   33640   41090    NaN    NaN

[1562 rows x 26 columns]

In [0]:
countyrent.replace('**', 0, inplace=True)

In [7]:
countyrent[countyrent['LOC_Q'].str.isalnum() == False]

AttributeError: ignored

In [8]:
countyrent[countyrent['OCC_TITLE'].str.contains('Budget Analyst')].sort_values(by='LOC_Q',ascending=False)[:10]

       Unnamed: 0  AREA  ST  ... A_PCT90 ANNUAL HOURLY
5592         5592    11  DC  ...  126060    NaN    NaN
788           788     2  AK  ...  105850    NaN    NaN
32451       32451    51  VA  ...  126070    NaN    NaN
35909       35909    66  GU  ...   76880    NaN    NaN
13972       13972    24  MD  ...  124390    NaN    NaN
21863       21863    35  NM  ...  107040    NaN    NaN
4358         4358     9  CT  ...  109320    NaN    NaN
36181       36181    72  PR  ...   69000    NaN    NaN
21103       21103    34  NJ  ...  123710    NaN    NaN
18450       18450    30  MT  ...   79600    NaN    NaN

[10 rows x 26 columns]

In [9]:
countyrent[countyrent['OCC_TITLE'].str.contains('Budget Analyst')].sort_values(by='TOT_EMP',ascending=False)[:10]

       Unnamed: 0  AREA  ST  ... A_PCT90 ANNUAL HOURLY
2790         2790     6  CA  ...  133020    NaN    NaN
30378       30378    48  TX  ...  116550    NaN    NaN
32451       32451    51  VA  ...  126070    NaN    NaN
6121         6121    12  FL  ...  103260    NaN    NaN
22521       22521    36  NY  ...  110570    NaN    NaN
13972       13972    24  MD  ...  124390    NaN    NaN
21103       21103    34  NJ  ...  123710    NaN    NaN
5592         5592    11  DC  ...  126060    NaN    NaN
6916         6916    13  GA  ...  102520    NaN    NaN
14730       14730    25  MA  ...  122010    NaN    NaN

[10 rows x 26 columns]

In [9]:
countyrent['Wage_Premium'] = countyrent[countyrent['OCC_TITLE'].str.contains('

SyntaxError: ignored

In [10]:
countyrent['A_MEDIAN'] = countyrent['A_MEDIAN'].astype(str)
countyrent.replace('*', 0, inplace=True)
countyrent.replace('#', 0, inplace=True)
countyrent[countyrent['A_MEDIAN'].str.isdigit() == False]['A_MEDIAN'].value_counts()

ERROR! Session/line number was not unique in database. History logging moved to new session 59

Series([], Name: A_MEDIAN, dtype: int64)

In [0]:
countyrent['A_MEDIAN'] = countyrent['A_MEDIAN'].astype(int)

In [12]:
countyrent['A_MEDIAN']

0         33740
1         95710
2        189920
3        100980
4         19210
          ...
36892     23430
36893     28240
36894     24870
36895     27400
36896     20450
Name: A_MEDIAN, Length: 36897, dtype: int64

In [0]:
states_median_income = countyrent.groupby('STATE')['A_MEDIAN'].agg('median')

In [14]:
countyrent.groupby('STATE')['A_MEDIAN'].median()

STATE
Alabama                 40590
Alaska                  56300
Arizona                 43340
Arkansas                38875
California              53240
Colorado                47630
Connecticut             53805
Delaware                44810
District of Columbia    61675
Florida                 41040
Georgia                 42720
Guam                    31410
Hawaii                  51390
Idaho                   41030
Illinois                49765
Indiana                 41065
Iowa                    43010
Kansas                  43155
Kentucky                42695
Louisiana               40880
Maine                   44970
Maryland                49280
Massachusetts           53760
Michigan                44255
Minnesota               49395
Mississippi             37840
Missouri                44010
Montana                 42390
Nebraska                42830
Nevada                  48050
New Hampshire           45480
New Jersey              53400
New Mexico              42530
New York                53585
North Carolina          43080
North Dakota            46590
Ohio                    44030
Oklahoma                39865
Oregon                  48450
Pennsylvania            46470
Puerto Rico             25460
Rhode Island            48690
South Carolina          40840
South Dakota            39380
Tennessee               41540
Texas                   44430
Utah                    43770
Vermont                 43090
Virgin Islands          34240
Virginia                45555
Washington              53250
West Virginia           41025
Wisconsin               45235
Wyoming                 47030
Name: A_MEDIAN, dtype: int64

In [0]:
countyrent['test'] = countyrent.groupby('STATE')['A_MEDIAN'].median()

In [16]:
countyrent

       Unnamed: 0  AREA  ST           STATE  ... A_PCT90 ANNUAL HOURLY  test
0               0     1  AL         Alabama  ...   79630    NaN    NaN   NaN
1               1     1  AL         Alabama  ...  187330    NaN    NaN   NaN
2               2     1  AL         Alabama  ...       0    NaN    NaN   NaN
3               3     1  AL         Alabama  ...       0    NaN    NaN   NaN
4               4     1  AL         Alabama  ...   63390    1.0    NaN   NaN
...           ...   ...  ..             ...  ...     ...    ...    ...   ...
36892       36892    78  VI  Virgin Islands  ...   30560    NaN    NaN   NaN
36893       36893    78  VI  Virgin Islands  ...   44290    NaN    NaN   NaN
36894       36894    78  VI  Virgin Islands  ...   41290    NaN    NaN   NaN
36895       36895    78  VI  Virgin Islands  ...   41090    NaN    NaN   NaN
36896       36896    78  VI  Virgin Islands  ...   24270    NaN    NaN   NaN

[36897 rows x 27 columns]

In [17]:
states_median_income.index

Index(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado',
       'Connecticut', 'Delaware', 'District of Columbia', 'Florida', 'Georgia',
       'Guam', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas',
       'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts',
       'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana',
       'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico',
       'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma',
       'Oregon', 'Pennsylvania', 'Puerto Rico', 'Rhode Island',
       'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah',
       'Vermont', 'Virgin Islands', 'Virginia', 'Washington', 'West Virginia',
       'Wisconsin', 'Wyoming'],
      dtype='object', name='STATE')

In [18]:
states_median_income.values

array([40590, 56300, 43340, 38875, 53240, 47630, 53805, 44810, 61675,
       41040, 42720, 31410, 51390, 41030, 49765, 41065, 43010, 43155,
       42695, 40880, 44970, 49280, 53760, 44255, 49395, 37840, 44010,
       42390, 42830, 48050, 45480, 53400, 42530, 53585, 43080, 46590,
       44030, 39865, 48450, 46470, 25460, 48690, 40840, 39380, 41540,
       44430, 43770, 43090, 34240, 45555, 53250, 41025, 45235, 47030])

In [0]:
income_dict = dict()
for i in range(len(states_median_income.index)):
  income_dict[states_median_income.index[i]] = states_median_income.values[i]

In [20]:
income_dict

{'Alabama': 40590,
 'Alaska': 56300,
 'Arizona': 43340,
 'Arkansas': 38875,
 'California': 53240,
 'Colorado': 47630,
 'Connecticut': 53805,
 'Delaware': 44810,
 'District of Columbia': 61675,
 'Florida': 41040,
 'Georgia': 42720,
 'Guam': 31410,
 'Hawaii': 51390,
 'Idaho': 41030,
 'Illinois': 49765,
 'Indiana': 41065,
 'Iowa': 43010,
 'Kansas': 43155,
 'Kentucky': 42695,
 'Louisiana': 40880,
 'Maine': 44970,
 'Maryland': 49280,
 'Massachusetts': 53760,
 'Michigan': 44255,
 'Minnesota': 49395,
 'Mississippi': 37840,
 'Missouri': 44010,
 'Montana': 42390,
 'Nebraska': 42830,
 'Nevada': 48050,
 'New Hampshire': 45480,
 'New Jersey': 53400,
 'New Mexico': 42530,
 'New York': 53585,
 'North Carolina': 43080,
 'North Dakota': 46590,
 'Ohio': 44030,
 'Oklahoma': 39865,
 'Oregon': 48450,
 'Pennsylvania': 46470,
 'Puerto Rico': 25460,
 'Rhode Island': 48690,
 'South Carolina': 40840,
 'South Dakota': 39380,
 'Tennessee': 41540,
 'Texas': 44430,
 'Utah': 43770,
 'Vermont': 43090,
 'Virgin Islands': 34240,
 'Virginia': 45555,
 'Washington': 53250,
 'West Virginia': 41025,
 'Wisconsin': 45235,
 'Wyoming': 47030}

In [0]:
countyrent['state_median'] = countyrent.groupby('STATE')['A_MEDIAN'].agg('median')

In [0]:
countyrent['state_median_2']= countyrent.apply(lambda x : income_dict[x['STATE']] if x['STATE'] in income_dict else 0,axis=1)

In [23]:
countyrent

       Unnamed: 0  AREA  ST  ... test state_median state_median_2
0               0     1  AL  ...  NaN          NaN          40590
1               1     1  AL  ...  NaN          NaN          40590
2               2     1  AL  ...  NaN          NaN          40590
3               3     1  AL  ...  NaN          NaN          40590
4               4     1  AL  ...  NaN          NaN          40590
...           ...   ...  ..  ...  ...          ...            ...
36892       36892    78  VI  ...  NaN          NaN          34240
36893       36893    78  VI  ...  NaN          NaN          34240
36894       36894    78  VI  ...  NaN          NaN          34240
36895       36895    78  VI  ...  NaN          NaN          34240
36896       36896    78  VI  ...  NaN          NaN          34240

[36897 rows x 29 columns]

In [0]:
countyrent['wage_premium']= countyrent['A_MEDIAN'] / countyrent['state_median_2']

In [25]:
countyrent[countyrent['OCC_TITLE'] == 'Budget Analysts'].sort_values(by='wage_premium',ascending=False)

       Unnamed: 0  AREA  ST  ... state_median state_median_2 wage_premium
52             52     1  AL  ...          NaN          40590     1.993348
32451       32451    51  VA  ...          NaN          45555     1.969268
13972       13972    24  MD  ...          NaN          49280     1.820414
15483       15483    26  MI  ...          NaN          44255     1.779460
35909       35909    66  GU  ...          NaN          31410     1.772047
25475       25475    40  OK  ...          NaN          39865     1.761445
21863       21863    35  NM  ...          NaN          42530     1.732894
31186       31186    49  UT  ...          NaN          43770     1.704592
6121         6121    12  FL  ...          NaN          41040     1.703460
10469       10469    19  IA  ...          NaN          43010     1.686817
3603         3603     8  CO  ...          NaN          47630     1.671845
9698         9698    18  IN  ...          NaN          41065     1.659564
27758       27758    44  RI  ...          NaN          48690     1.649620
28329       28329    45  SC  ...          NaN          40840     1.648874
30378       30378    48  TX  ...          NaN          44430     1.646860
24684       24684    39  OH  ...          NaN          44030     1.644561
29608       29608    47  TN  ...          NaN          41540     1.642754
31893       31893    50  VT  ...          NaN          43090     1.636110
20447       20447    33  NH  ...          NaN          45480     1.636104
2790         2790     6  CA  ...          NaN          53240     1.629038
5592         5592    11  DC  ...          NaN          61675     1.624807
36181       36181    72  PR  ...          NaN          25460     1.621367
17008       17008    28  MS  ...          NaN          37840     1.620772
23315       23315    37  NC  ...          NaN          43080     1.618849
6916         6916    13  GA  ...          NaN          42720     1.588249
1350         1350     4  AZ  ...          NaN          43340     1.577988
13342       13342    23  ME  ...          NaN          44970     1.573716
5047         5047    10  DE  ...          NaN          44810     1.573086
34635       34635    55  WI  ...          NaN          45235     1.561844
33967       33967    54  WV  ...          NaN          41025     1.553443
7670         7670    15  HI  ...          NaN          51390     1.549134
14730       14730    25  MA  ...          NaN          53760     1.548363
12617       12617    22  LA  ...          NaN          40880     1.547701
16260       16260    27  MN  ...          NaN          49395     1.546715
8266         8266    16  ID  ...          NaN          41030     1.529125
26208       26208    41  OR  ...          NaN          48450     1.528586
4358         4358     9  CT  ...          NaN          53805     1.521234
29033       29033    46  SD  ...          NaN          39380     1.520061
26966       26966    42  PA  ...          NaN          46470     1.519475
36746       36746    78  VI  ...          NaN          34240     1.514311
11185       11185    20  KS  ...          NaN          43155     1.514309
21103       21103    34  NJ  ...          NaN          53400     1.511985
8914         8914    17  IL  ...          NaN          49765     1.463277
17693       17693    29  MO  ...          NaN          44010     1.451261
24068       24068    38  ND  ...          NaN          46590     1.445160
18450       18450    30  MT  ...          NaN          42390     1.438783
35376       35376    56  WY  ...          NaN          47030     1.422709
22521       22521    36  NY  ...          NaN          53585     1.404498
19767       19767    32  NV  ...          NaN          48050     1.401249
33205       33205    53  WA  ...          NaN          53250     1.371268
788           788     2  AK  ...          NaN          56300     1.369982
19089       19089    31  NE  ...          NaN          42830     1.259164
11887       11887    21  KY  ...          NaN          42695     1.242534
2098         2098     5  AR  ...          NaN          38875     1.221350

[54 rows x 30 columns]

In [25]:
The state with the least amount of wage premium for budget analyst compared to the average is Arkansas and Alabama is the best

SyntaxError: ignored

In [26]:
countyrent['rank'] = countyrent.groupby("OCC_TITLE")["wage_premium"].rank("dense", ascending=False)
#this groups per job then gets the wage premium column and ranks each group descending

ERROR! Session/line number was not unique in database. History logging moved to new session 60

In [27]:
countyrent[countyrent['STATE']== 'Minnesota'][['OCC_TITLE','rank']].sort_values(by='rank',ascending=True)[:30]

                                               OCC_TITLE  rank
16864            Tailors, Dressmakers, and Custom Sewers   1.0
16744                       Plasterers and Stucco Masons   1.0
16545                                  Psychiatric Aides   1.0
16547                                          Orderlies   1.0
16295                               Biomedical Engineers   1.0
16468  Entertainers and Performers, Sports and Relate...   1.0
16467                              Musicians and Singers   1.0
16464                                            Dancers   1.0
16459                                             Actors   1.0
16499                                           Surgeons   1.0
16603               Building Cleaning Workers, All Other   2.0
16466                      Music Directors and Composers   2.0
16945                          Hoist and Winch Operators   2.0
16735                Drywall and Ceiling Tile Installers   2.0
16529                             Surgical Technologists   2.0
16929       Railroad Brake, Signal, and Switch Operators   2.0
16671           Credit Authorizers, Checkers, and Clerks   3.0
16752  Helpers--Painters, Paperhangers, Plasterers, a...   3.0
16531                     Ophthalmic Medical Technicians   3.0
16577                                    Crossing Guards   3.0
16378           Arbitrators, Mediators, and Conciliators   3.0
16731                              Construction Laborers   3.0
16749  Helpers--Brickmasons, Blockmasons, Stonemasons...   3.0
16687            Police, Fire, and Ambulance Dispatchers   3.0
16551                           Physical Therapist Aides   3.0
16553                                  Dental Assistants   3.0
16480                                    Radio Operators   3.0
16223  Farmers, Ranchers, and Other Agricultural Mana...   3.0
16555                        Medical Equipment Preparers   4.0
16747                                Sheet Metal Workers   4.0

In [0]:
#in minnesota the jobs with the most wage premium relative to all other states meaning that if all the dentists from all the states were
#compared from their salary to the average in each state which state pays the relative most amount to dentists? Minnesota has the
#highest relative pay for medical types of fields. The medical field must pay a good amount in minnesota economy more than other states

In [28]:
#state with highest median pay overall
countyrent.groupby(by='STATE')['state_median_2'].agg('min').sort_values(ascending=False)
#minnesota is 11th

STATE
District of Columbia    61675
Alaska                  56300
Connecticut             53805
Massachusetts           53760
New York                53585
New Jersey              53400
Washington              53250
California              53240
Hawaii                  51390
Illinois                49765
Minnesota               49395
Maryland                49280
Rhode Island            48690
Oregon                  48450
Nevada                  48050
Colorado                47630
Wyoming                 47030
North Dakota            46590
Pennsylvania            46470
Virginia                45555
New Hampshire           45480
Wisconsin               45235
Maine                   44970
Delaware                44810
Texas                   44430
Michigan                44255
Ohio                    44030
Missouri                44010
Utah                    43770
Arizona                 43340
Kansas                  43155
Vermont                 43090
North Carolina          43080
Iowa                    43010
Nebraska                42830
Georgia                 42720
Kentucky                42695
New Mexico              42530
Montana                 42390
Tennessee               41540
Indiana                 41065
Florida                 41040
Idaho                   41030
West Virginia           41025
Louisiana               40880
South Carolina          40840
Alabama                 40590
Oklahoma                39865
South Dakota            39380
Arkansas                38875
Mississippi             37840
Virgin Islands          34240
Guam                    31410
Puerto Rico             25460
Name: state_median_2, dtype: int64

In [29]:
#which states have the most #1 wage premium jobs- largest positive difference between average and their salary
countyrent[countyrent['rank']==1][['STATE','OCC_TITLE']]['STATE'].value_counts()
#pandas counts al the 0's in the ranking for the median somehow so there were more relatively high paying jobs but probably because
#there was not data

Puerto Rico             103
Guam                     39
Virgin Islands           35
Virginia                 33
New Mexico               32
California               30
Mississippi              29
Hawaii                   28
South Dakota             27
Delaware                 26
Alabama                  26
Illinois                 25
District of Columbia     24
Louisiana                24
Oklahoma                 22
Georgia                  20
New York                 19
Indiana                  19
South Carolina           17
Oregon                   17
Vermont                  17
Missouri                 17
Wyoming                  17
Florida                  16
Nevada                   16
Kentucky                 16
Texas                    16
Maryland                 16
Alaska                   15
Iowa                     15
Idaho                    15
Tennessee                14
West Virginia            13
North Dakota             13
New Jersey               13
Rhode Island             12
Arizona                  12
Washington               12
Pennsylvania             11
North Carolina           11
Arkansas                 11
Montana                  11
Wisconsin                11
Ohio                     10
New Hampshire            10
Minnesota                10
Nebraska                 10
Colorado                  9
Connecticut               9
Massachusetts             8
Michigan                  7
Kansas                    7
Utah                      7
Maine                     7
Name: STATE, dtype: int64

In [30]:
countyrent[countyrent['STATE'] == 'Puerto Rico']

       Unnamed: 0  AREA  ST  ... state_median_2 wage_premium  rank
36133       36133    72  PR  ...          25460     0.818146  44.0
36134       36134    72  PR  ...          25460     2.409269   8.0
36135       36135    72  PR  ...          25460     3.791438  11.0
36136       36136    72  PR  ...          25460     2.604478   6.0
36137       36137    72  PR  ...          25460     3.246269   1.0
...           ...   ...  ..  ...            ...          ...   ...
36715       36715    72  PR  ...          25460     0.715240   1.0
36716       36716    72  PR  ...          25460     0.858602  24.0
36717       36717    72  PR  ...          25460     1.123723   7.0
36718       36718    72  PR  ...          25460     0.727808  36.0
36719       36719    72  PR  ...          25460     0.753339  19.0

[587 rows x 31 columns]

In [31]:
countyrent[countyrent['STATE'] == 'Puerto Rico']['STATE']

36133    Puerto Rico
36134    Puerto Rico
36135    Puerto Rico
36136    Puerto Rico
36137    Puerto Rico
            ...
36715    Puerto Rico
36716    Puerto Rico
36717    Puerto Rico
36718    Puerto Rico
36719    Puerto Rico
Name: STATE, Length: 587, dtype: object

In [32]:
countyrent[(countyrent['STATE'] == 'Puerto Rico') & (countyrent['A_MEDIAN'] < 1) ]['A_MEDIAN'].count()

12

In [33]:
countyrent[(countyrent['STATE'] == 'Puerto Rico') & (countyrent['A_MEDIAN'] > 1) ]['A_MEDIAN'].count()

575

In [34]:
countyrent[(countyrent['STATE'] == 'Puerto Rico') & (countyrent['A_MEDIAN'] < 1) ]

       Unnamed: 0  AREA  ST  ... state_median_2 wage_premium  rank
36222       36222    72  PR  ...          25460          0.0  50.0
36234       36234    72  PR  ...          25460          0.0  30.0
36239       36239    72  PR  ...          25460          0.0  48.0
36249       36249    72  PR  ...          25460          0.0  44.0
36283       36283    72  PR  ...          25460          0.0  24.0
36330       36330    72  PR  ...          25460          0.0  49.0
36336       36336    72  PR  ...          25460          0.0   1.0
36339       36339    72  PR  ...          25460          0.0   1.0
36524       36524    72  PR  ...          25460          0.0  51.0
36634       36634    72  PR  ...          25460          0.0  43.0
36651       36651    72  PR  ...          25460          0.0  43.0
36706       36706    72  PR  ...          25460          0.0  47.0

[12 rows x 31 columns]

In [35]:
#top paying jobs puerto rico
countyrent[countyrent['STATE'] == 'Puerto Rico'][['STATE','A_MEDIAN','OCC_TITLE','wage_premium','rank']].sort_values(by='A_MEDIAN',ascending=False)[:20]

             STATE  A_MEDIAN  ... wage_premium  rank
36298  Puerto Rico    111440  ...     4.377062   1.0
36367  Puerto Rico    109490  ...     4.300471   7.0
36144  Puerto Rico    106530  ...     4.184211   1.0
36154  Puerto Rico    103710  ...     4.073449   1.0
36690  Puerto Rico     98770  ...     3.879419   1.0
36155  Puerto Rico     97170  ...     3.816575   2.0
36135  Puerto Rico     96530  ...     3.791438  11.0
36361  Puerto Rico     92450  ...     3.631186   2.0
36246  Puerto Rico     92360  ...     3.627651   1.0
36274  Puerto Rico     91120  ...     3.578947   4.0
36287  Puerto Rico     90480  ...     3.553810   1.0
36137  Puerto Rico     82650  ...     3.246269   1.0
36139  Puerto Rico     82260  ...     3.230951   4.0
36160  Puerto Rico     82230  ...     3.229772   1.0
36288  Puerto Rico     81900  ...     3.216811   1.0
36375  Puerto Rico     78460  ...     3.081697   1.0
36147  Puerto Rico     78060  ...     3.065986   3.0
36401  Puerto Rico     77260  ...     3.034564   1.0
36206  Puerto Rico     76860  ...     3.018853   1.0
36365  Puerto Rico     76580  ...     3.007855  37.0

[20 rows x 5 columns]

In [0]:
#apparently puerto rico just has a lot of people who make very little compared to the most important higher earning jobs.
#that is why they have the most highest ranked job premiums per the median.

In [0]:
f = pd.DataFrame(({'a':[0,0,1,1], 'b':[0,1,0,1]}))

In [38]:
f

   a  b
0  0  0
1  0  1
2  1  0
3  1  1

In [39]:
f.T

   0  1  2  3
a  0  0  1  1
b  0  1  0  1

In [40]:
f[(f != 0).any(axis=1)]

   a  b
1  0  1
2  1  0
3  1  1

In [41]:
f[f>0]

     a    b
0  NaN  NaN
1  NaN  1.0
2  1.0  NaN
3  1.0  1.0

In [0]:
#the best states for analysts
wage_premium_analysts = countyrent[countyrent['OCC_TITLE'].str.contains('Analysts')].groupby('STATE')['wage_premium'].agg('sum').sort_values(ascending=False)

In [43]:
#the best states based on having the highest median earnings. The more earnings in general that I can make the better
#this way if I save 10% for retirement then it is better because then I can have a lot relative to other states in case I move there
wage_premium_analysts = pd.DataFrame(wage_premium_analysts)
#wage_premium_analysts['earnings'] = countyrent['state_median_2']
wage_premium_analysts

                      wage_premium
STATE
Alabama                  17.414634
North Carolina           16.647864
Virginia                 16.104489
Texas                    16.078551
Florida                  15.638645
Maryland                 15.596591
New York                 15.549128
Colorado                 15.510393
Arizona                  15.222658
Ohio                     15.064956
California               14.671112
Missouri                 14.667348
Idaho                    14.661955
New Jersey               14.651311
New Hampshire            14.610378
District of Columbia     14.587272
Washington               14.582723
South Carolina           14.481391
Arkansas                 14.450932
Indiana                  14.406916
Delaware                 14.396117
Puerto Rico              14.336999
New Mexico               14.234423
Tennessee                14.221955
Mississippi              14.202431
Utah                     14.166781
Wisconsin                14.043992
Michigan                 13.943057
Illinois                 13.914197
Pennsylvania             13.820960
Georgia                  13.796114
Rhode Island             13.773670
Iowa                     13.524529
Louisiana                13.506115
Vermont                  13.455094
Nevada                   13.386889
Kentucky                 13.345825
Oklahoma                 13.295874
Minnesota                13.191416
Kansas                   13.099988
Oregon                   13.085655
Connecticut              12.930583
North Dakota             12.890534
Massachusetts            12.721726
Maine                    12.708917
West Virginia            12.594516
Montana                  12.476999
Hawaii                   12.459039
Nebraska                 12.296288
South Dakota             12.011935
Wyoming                  10.119923
Alaska                    9.785435
Virgin Islands            7.087033
Guam                      6.700096

In [44]:
wage_premium_analysts['earnings'] = unique

NameError: ignored

In [0]:
wage_premium_analysts.sort_index(inplace=True)

In [0]:
unique = countyrent.groupby('STATE')['state_median_2'].agg('min')

In [47]:
wage_premium_analysts['overall'] = wage_premium_analysts['wage_premium'] * wage_premium_analysts['earnings']

KeyError: ignored

In [48]:
wage_premium_analysts['overall'].sort_values(ascending=False)

KeyError: ignored

the best place for analysts overall is washington dc because they have both a high amount of income and a high amount of premium for analysys meaning that analysts make a lot relative to everywhere and relative to washington dc.

In [0]:
#the highest ratio between the median and the 10thpercentile since I am starting out I want to find states where the entry level
#analysts get paid the most relative to the median

In [49]:
countyrent.groupby('STATE')[['A_PCT25','A_MEDIAN','OCC_TITLE','wage_premium','rank']].agg('mean').sort_values(by='A_MEDIAN',ascending=False)

                           A_PCT25      A_MEDIAN  wage_premium       rank
STATE
District of Columbia  53402.662835  67187.816092      1.089385  30.532567
California            47381.803681  61193.472393      1.149389  24.782822
New York              46598.040201  59392.487437      1.108379  27.368090
Massachusetts         47253.014608  58716.387782      1.092195  26.718459
Alaska                47926.075269  58370.663082      1.036779  30.897849
Connecticut           46842.925072  58052.002882      1.078933  29.069164
Maryland              45319.828496  58022.203166      1.177399  23.596306
Washington            47902.133508  57925.405759      1.087801  26.365183
New Jersey            46327.493438  57849.842520      1.083330  27.653543
Rhode Island          45644.348592  55163.573944      1.132955  22.468310
Hawaii                44015.430017  55150.370995      1.073173  28.284992
Illinois              42550.447570  55049.079284      1.106181  29.801790
Colorado              43799.894180  54679.325397      1.148002  22.526455
Minnesota             44875.080000  54469.933333      1.102742  24.457333
Oregon                44091.624835  54214.187583      1.118972  24.922061
New Hampshire         43616.380368  52740.245399      1.159636  19.743865
Pennsylvania          42348.316583  52737.324121      1.134868  24.820352
Virginia              41217.082228  52449.986737      1.151355  21.610080
Delaware              42359.232176  52106.819013      1.162839  19.881170
Texas                 40233.600493  51938.705302      1.169001  22.890259
Nevada                42275.380117  51925.657895      1.080659  27.877193
Wyoming               41901.926606  51040.128440      1.085267  29.093578
North Dakota          41197.692308  50904.042553      1.092596  25.808511
Wisconsin             41297.072193  50730.828877      1.121495  25.181818
Michigan              39696.533505  50441.030928      1.139782  22.007732
North Carolina        40150.396825  50362.420635      1.169044  22.985450
Ohio                  39811.668774  50198.280657      1.140093  22.788875
Arizona               39957.226667  49832.520000      1.149804  20.746667
Vermont               40918.529946  49763.303085      1.154869  18.254083
Missouri              39173.738562  49683.163399      1.128906  25.695425
Georgia               39482.721268  49625.693527      1.161650  22.597094
Maine                 40706.022364  49584.408946      1.102611  28.354633
New Mexico            39791.282443  49511.480916      1.164154  24.835115
Kansas                38718.593750  49281.960227      1.141976  26.255682
Utah                  39326.132208  48936.343179      1.118034  25.825598
Florida               38240.967337  48807.148241      1.189258  18.611809
Iowa                  40438.744770  48670.543933      1.131610  21.648536
Alabama               38144.756098  48224.769648      1.188095  21.379404
Tennessee             37340.571429  47509.922078      1.143715  23.192208
Kentucky              37844.586777  47394.641873      1.110075  27.163912
South Carolina        38077.868163  47138.485273      1.154223  21.791024
Nebraska              39058.757396  47130.784024      1.100415  23.640533
Idaho                 37933.462133  46852.210201      1.141901  23.165379
Montana               38433.044164  46841.372240      1.105010  25.376972
Louisiana             36643.178082  46578.000000      1.139384  24.273973
South Dakota          39369.310954  46529.010601      1.181539  19.869258
Indiana               37571.126943  46474.598446      1.131733  20.005181
West Virginia         36274.369369  46238.558559      1.127082  27.298799
Oklahoma              36099.318801  45675.885559      1.145764  21.613079
Arkansas              35629.389535  44897.645349      1.154923  23.068314
Mississippi           35461.127379  43878.052709      1.159568  20.931186
Virgin Islands        32126.779661  39845.141243      1.163702  14.039548
Guam                  29832.162162  37087.606178      1.180758  18.073359
Puerto Rico           24986.320273  31614.667802      1.241739  20.269165

In [0]:
data = countyrent.groupby('STATE')[['A_PCT10','A_PCT25','A_MEDIAN','OCC_TITLE','wage_premium','rank']].agg('mean').sort_values(by='A_MEDIAN',ascending=False)

In [0]:
data['ratiopercentiles2550'] = data['A_PCT25'] / data['A_MEDIAN']

In [52]:
data.sort_values(by='ratiopercentiles2550',ascending=False)

                           A_PCT10  ...  ratiopercentiles2550
STATE                               ...
South Dakota          34799.699647  ...              0.846124
Iowa                  32901.868898  ...              0.830867
Nebraska              32865.946746  ...              0.828731
Rhode Island          37432.218310  ...              0.827436
New Hampshire         36340.000000  ...              0.827004
Washington            39159.267016  ...              0.826962
Minnesota             36771.320000  ...              0.823850
Vermont               34865.281307  ...              0.822263
Alaska                39485.788530  ...              0.821064
Wyoming               35085.724771  ...              0.820960
Maine                 34512.124601  ...              0.820944
Montana               31482.886435  ...              0.820494
Nevada                34349.342105  ...              0.814152
Wisconsin             33969.558824  ...              0.814043
Oregon                36270.198151  ...              0.813286
Delaware              36324.588665  ...              0.812931
Idaho                 30388.222566  ...              0.809641
North Dakota          34487.561375  ...              0.809321
Indiana               30930.012953  ...              0.808423
Mississippi           28839.194729  ...              0.808175
South Carolina        31005.343619  ...              0.807787
Connecticut           38248.804035  ...              0.806913
Virgin Islands        26795.480226  ...              0.806291
Massachusetts         38569.150066  ...              0.804767
Guam                  25469.073359  ...              0.804370
New Mexico            33043.847328  ...              0.803678
Utah                  31180.801688  ...              0.803618
Pennsylvania          33852.324121  ...              0.803005
Arizona               32702.373333  ...              0.801830
Colorado              35771.362434  ...              0.801032
New Jersey            37759.278215  ...              0.800823
Kentucky              31154.696970  ...              0.798499
Hawaii                36120.539629  ...              0.798099
North Carolina        33388.214286  ...              0.797229
Georgia               31997.754293  ...              0.795610
District of Columbia  43359.233716  ...              0.794827
Arkansas              29218.880814  ...              0.793569
Ohio                  32043.021492  ...              0.793088
Alabama               31054.566396  ...              0.790979
Puerto Rico           20795.195911  ...              0.790339
Oklahoma              29563.978202  ...              0.790336
Missouri              31222.967320  ...              0.788471
Michigan              31774.987113  ...              0.786989
Louisiana             29627.643836  ...              0.786706
Tennessee             30035.727273  ...              0.785953
Virginia              33061.830239  ...              0.785836
Kansas                31398.110795  ...              0.785654
New York              36852.675879  ...              0.784578
West Virginia         29842.627628  ...              0.784505
Florida               30581.984925  ...              0.783512
Maryland              36152.255937  ...              0.781077
Texas                 31073.995068  ...              0.774636
California            37465.705521  ...              0.774295
Illinois              33406.342711  ...              0.772955

[54 rows x 6 columns]

In [53]:
#wage premium for the jobs multiplied by the ratio of 25th percentile to 50th percentile
data['overall'] = data['wage_premium'] * data['ratiopercentiles2550']
data.sort_values(by='overall',ascending=False)

                           A_PCT10  ...   overall
STATE                               ...
South Dakota          34799.699647  ...  0.999729
Puerto Rico           20795.195911  ...  0.981395
New Hampshire         36340.000000  ...  0.959023
Guam                  25469.073359  ...  0.949766
Vermont               34865.281307  ...  0.949606
Delaware              36324.588665  ...  0.945308
Iowa                  32901.868898  ...  0.940217
Alabama               31054.566396  ...  0.939757
Virgin Islands        26795.480226  ...  0.938282
Rhode Island          37432.218310  ...  0.937448
Mississippi           28839.194729  ...  0.937133
New Mexico            33043.847328  ...  0.935605
South Carolina        31005.343619  ...  0.932367
North Carolina        33388.214286  ...  0.931996
Florida               30581.984925  ...  0.931797
Idaho                 30388.222566  ...  0.924530
Georgia               31997.754293  ...  0.924221
Arizona               32702.373333  ...  0.921948
Maryland              36152.255937  ...  0.919639
Colorado              35771.362434  ...  0.919586
Arkansas              29218.880814  ...  0.916512
Indiana               30930.012953  ...  0.914918
Wisconsin             33969.558824  ...  0.912945
Nebraska              32865.946746  ...  0.911949
Pennsylvania          33852.324121  ...  0.911304
Oregon                36270.198151  ...  0.910044
Minnesota             36771.320000  ...  0.908494
Montana               31482.886435  ...  0.906654
Texas                 31073.995068  ...  0.905550
Oklahoma              29563.978202  ...  0.905539
Maine                 34512.124601  ...  0.905182
Virginia              33061.830239  ...  0.904776
Ohio                  32043.021492  ...  0.904194
Washington            39159.267016  ...  0.899571
Tennessee             30035.727273  ...  0.898906
Utah                  31180.801688  ...  0.898472
Kansas                31398.110795  ...  0.897198
Michigan              31774.987113  ...  0.896995
Louisiana             29627.643836  ...  0.896360
Wyoming               35085.724771  ...  0.890962
Missouri              31222.967320  ...  0.890110
California            37465.705521  ...  0.889966
Kentucky              31154.696970  ...  0.886394
North Dakota          34487.561375  ...  0.884260
West Virginia         29842.627628  ...  0.884202
Nevada                34349.342105  ...  0.879821
Massachusetts         38569.150066  ...  0.878962
Connecticut           38248.804035  ...  0.870605
New York              36852.675879  ...  0.869610
New Jersey            37759.278215  ...  0.867556
District of Columbia  43359.233716  ...  0.865872
Hawaii                36120.539629  ...  0.856498
Illinois              33406.342711  ...  0.855028
Alaska                39485.788530  ...  0.851262

[54 rows x 7 columns]

In [0]:
data['ratiopercentiles1025'] = data['A_PCT10'] / data['A_MEDIAN']

In [55]:
data['overall_2'] = data['wage_premium'] * data['ratiopercentiles1025']
data.sort_values(by='overall_2',ascending=False)

                           A_PCT10  ...  overall_2
STATE                               ...
South Dakota          34799.699647  ...   0.883690
Puerto Rico           20795.195911  ...   0.816779
Guam                  25469.073359  ...   0.810859
Delaware              36324.588665  ...   0.810636
Vermont               34865.281307  ...   0.809127
New Hampshire         36340.000000  ...   0.799033
Virgin Islands        26795.480226  ...   0.782578
New Mexico            33043.847328  ...   0.776954
North Carolina        33388.214286  ...   0.775028
Rhode Island          37432.218310  ...   0.768787
Maine                 34512.124601  ...   0.767448
Nebraska              32865.946746  ...   0.767358
Alabama               31054.566396  ...   0.765079
Iowa                  32901.868898  ...   0.764982
Mississippi           28839.194729  ...   0.762135
South Carolina        31005.343619  ...   0.759191
Arizona               32702.373333  ...   0.754554
Indiana               30930.012953  ...   0.753196
Arkansas              29218.880814  ...   0.751611
Colorado              35771.362434  ...   0.751026
Wisconsin             33969.558824  ...   0.750957
Georgia               31997.754293  ...   0.749011
Oregon                36270.198151  ...   0.748611
Wyoming               35085.724771  ...   0.746029
Florida               30581.984925  ...   0.745175
Minnesota             36771.320000  ...   0.744434
Montana               31482.886435  ...   0.742696
Oklahoma              29563.978202  ...   0.741602
Idaho                 30388.222566  ...   0.740634
North Dakota          34487.561375  ...   0.740235
Washington            39159.267016  ...   0.735385
Maryland              36152.255937  ...   0.733609
Kentucky              31154.696970  ...   0.729704
Pennsylvania          33852.324121  ...   0.728477
Ohio                  32043.021492  ...   0.727754
Kansas                31398.110795  ...   0.727566
West Virginia         29842.627628  ...   0.727425
Virginia              33061.830239  ...   0.725756
Louisiana             29627.643836  ...   0.724747
Tennessee             30035.727273  ...   0.723056
Michigan              31774.987113  ...   0.717998
Massachusetts         38569.150066  ...   0.717432
Nevada                34349.342105  ...   0.714867
Utah                  31180.801688  ...   0.712378
Connecticut           38248.804035  ...   0.710878
Missouri              31222.967320  ...   0.709452
New Jersey            37759.278215  ...   0.707103
California            37465.705521  ...   0.703713
District of Columbia  43359.233716  ...   0.703028
Hawaii                36120.539629  ...   0.702871
Alaska                39485.788530  ...   0.701346
Texas                 31073.995068  ...   0.699392
New York              36852.675879  ...   0.687742
Illinois              33406.342711  ...   0.671282

[54 rows x 9 columns]

In [0]:
#south dakota has a good wage premium and the best overall wage premium for analysts relative to the others
#and the difference between entry level and median analysts is small in south dakota

In [57]:
#the most wage premium states at the 10th percentile analysts
countyrent.groupby(by='STATE')[['A_PCT10','A_PCT25']].agg('median').sort_values(by='A_PCT10',ascending=False)

                      A_PCT10  A_PCT25
STATE
District of Columbia    38530    47715
Alaska                  35050    43035
Washington              34135    42460
Massachusetts           33780    41670
Connecticut             33325    41575
Minnesota               33235    40180
New Jersey              32840    41790
Hawaii                  32540    39990
Rhode Island            32345    38985
North Dakota            32230    38040
New York                32150    41245
Wyoming                 32070    37990
Delaware                31850    36090
Oregon                  31790    38010
California              31550    39490
Maryland                31375    38750
New Hampshire           30985    36635
Colorado                30960    37695
Maine                   30835    36165
Vermont                 30720    35490
Nevada                  30645    37400
Pennsylvania            29930    36760
Wisconsin               29840    36015
Illinois                29375    37580
South Dakota            29215    33795
Virginia                28905    35655
Iowa                    28400    34420
North Carolina          28250    34330
Nebraska                27880    33595
Ohio                    27800    34730
Arizona                 27640    34420
Michigan                27585    34520
Utah                    27580    34280
Indiana                 27445    33100
New Mexico              27420    34260
Kentucky                27285    33735
Missouri                27150    34030
Georgia                 27080    33670
Kansas                  27015    33770
Montana                 27010    33630
South Carolina          26830    32730
Texas                   26650    34060
Florida                 26580    32490
Alabama                 26575    32685
Tennessee               26470    33240
Idaho                   26450    32870
Oklahoma                26430    31835
Louisiana               26055    32315
West Virginia           25730    31680
Arkansas                25590    31300
Mississippi             24310    30070
Virgin Islands          22850    27130
Guam                    20940    25180
Puerto Rico             17150    19490

In [58]:
countyrent.groupby(by='STATE')[['A_PCT10','A_PCT25']].agg('median').sort_values(by='A_PCT25',ascending=False)

                      A_PCT10  A_PCT25
STATE
District of Columbia    38530    47715
Alaska                  35050    43035
Washington              34135    42460
New Jersey              32840    41790
Massachusetts           33780    41670
Connecticut             33325    41575
New York                32150    41245
Minnesota               33235    40180
Hawaii                  32540    39990
California              31550    39490
Rhode Island            32345    38985
Maryland                31375    38750
North Dakota            32230    38040
Oregon                  31790    38010
Wyoming                 32070    37990
Colorado                30960    37695
Illinois                29375    37580
Nevada                  30645    37400
Pennsylvania            29930    36760
New Hampshire           30985    36635
Maine                   30835    36165
Delaware                31850    36090
Wisconsin               29840    36015
Virginia                28905    35655
Vermont                 30720    35490
Ohio                    27800    34730
Michigan                27585    34520
Iowa                    28400    34420
Arizona                 27640    34420
North Carolina          28250    34330
Utah                    27580    34280
New Mexico              27420    34260
Texas                   26650    34060
Missouri                27150    34030
South Dakota            29215    33795
Kansas                  27015    33770
Kentucky                27285    33735
Georgia                 27080    33670
Montana                 27010    33630
Nebraska                27880    33595
Tennessee               26470    33240
Indiana                 27445    33100
Idaho                   26450    32870
South Carolina          26830    32730
Alabama                 26575    32685
Florida                 26580    32490
Louisiana               26055    32315
Oklahoma                26430    31835
West Virginia           25730    31680
Arkansas                25590    31300
Mississippi             24310    30070
Virgin Islands          22850    27130
Guam                    20940    25180
Puerto Rico             17150    19490

In [0]:
wageprem10th =countyrent.groupby(by='STATE')['A_PCT10'].agg('median').sort_values(ascending=False)
#countyrent['state_median_2']= countyrent.apply(lambda x : income_dict[x['STATE']] if x['STATE'] in income_dict else 0,axis=1)

In [0]:
state10th = dict()

In [61]:
wageprem10th.values

array([38530, 35050, 34135, 33780, 33325, 33235, 32840, 32540, 32345,
       32230, 32150, 32070, 31850, 31790, 31550, 31375, 30985, 30960,
       30835, 30720, 30645, 29930, 29840, 29375, 29215, 28905, 28400,
       28250, 27880, 27800, 27640, 27585, 27580, 27445, 27420, 27285,
       27150, 27080, 27015, 27010, 26830, 26650, 26580, 26575, 26470,
       26450, 26430, 26055, 25730, 25590, 24310, 22850, 20940, 17150])

In [0]:
for i in range(len(wageprem10th.index)):
  state10th[wageprem10th.index[i]] = wageprem10th.values[i]

In [0]:
countyrent['stateprem10th']= countyrent.apply(lambda x : wageprem10th[x['STATE']] if x['STATE'] in state10th else 0,axis=1)

In [0]:
countyrent['wage_prem_10th'] = countyrent['A_PCT10'] / countyrent['stateprem10th']

In [65]:
countyrent.groupby('STATE')[['wage_prem_10th','STATE']].sort_values(by='wage_prem_10th',ascending=False)

AttributeError: ignored

In [66]:
countyrent[countyrent['OCC_TITLE'].str.contains('Analysts')].groupby('STATE')['wage_prem_10th'].agg('sum').sort_values(ascending=False)

STATE
Texas                   16.009381
North Carolina          15.355398
Alabama                 15.023518
Virginia                14.906764
New York                14.446656
Ohio                    14.402518
California              14.392076
Colorado                14.289406
Maryland                14.245100
Missouri                14.154328
New Jersey              14.151949
Michigan                14.088091
Illinois                14.082383
Arizona                 14.073082
Florida                 14.054176
District of Columbia    13.954840
New Hampshire           13.893174
Washington              13.759777
New Mexico              13.719912
Nevada                  13.682819
Indiana                 13.488067
Pennsylvania            13.473438
Georgia                 13.356352
Connecticut             13.341335
Rhode Island            13.234812
Louisiana               13.231242
Mississippi             13.091732
Iowa                    13.045070
Kansas                  13.024246
South Carolina          13.013418
Wisconsin               12.984249
Tennessee               12.969022
Idaho                   12.945936
Delaware                12.912716
Massachusetts           12.833629
Vermont                 12.825846
Utah                    12.764322
Montana                 12.710848
Minnesota               12.680006
Oregon                  12.669078
Arkansas                12.601016
Maine                   12.434247
Oklahoma                12.224366
Hawaii                  12.178549
West Virginia           12.153129
Nebraska                12.041607
Kentucky                11.951622
North Dakota            11.436860
South Dakota            11.367106
Puerto Rico             11.202332
Wyoming                 10.127222
Alaska                   9.614551
Virgin Islands           7.836761
Guam                     6.467049
Name: wage_prem_10th, dtype: float64

In [67]:
wageprem25th =countyrent.groupby(by='STATE')['A_PCT25'].agg('median').sort_values(ascending=False)
state25th = dict()
for i in range(len(wageprem25th.index)):
  state25th[wageprem25th.index[i]] = wageprem25th.values[i]
countyrent['stateprem25th']= countyrent.apply(lambda x : wageprem25th[x['STATE']] if x['STATE'] in state25th else 0,axis=1)
countyrent['wage_prem_25th'] = countyrent['A_PCT25'] / countyrent['stateprem25th']
countyrent[countyrent['OCC_TITLE'].str.contains('Analysts')].groupby('STATE')['wage_prem_25th'].agg('sum').sort_values(ascending=False)

STATE
Alabama                 16.077100
North Carolina          15.893096
Texas                   15.810922
Virginia                15.670453
Colorado                14.953973
Maryland                14.952516
California              14.831096
New York                14.675718
Florida                 14.562635
Ohio                    14.562338
District of Columbia    14.324845
New Jersey              14.302225
Missouri                14.250955
Arizona                 14.169088
New Hampshire           14.103180
Michigan                14.022596
Idaho                   14.011561
Illinois                13.960085
Indiana                 13.950453
South Carolina          13.824015
Washington              13.820301
Delaware                13.805209
New Mexico              13.633975
Georgia                 13.547075
Pennsylvania            13.517682
Rhode Island            13.501347
Wisconsin               13.488824
Nevada                  13.451337
Mississippi             13.451280
Connecticut             13.298376
Iowa                    13.280941
Tennessee               13.272262
Vermont                 13.209073
Louisiana               13.199752
Oregon                  13.119968
Utah                    13.102392
Kansas                  12.973941
Puerto Rico             12.907645
Minnesota               12.892982
Arkansas                12.849521
Maine                   12.848334
Massachusetts           12.837773
Kentucky                12.748777
Oklahoma                12.718392
West Virginia           12.500316
Montana                 12.341957
North Dakota            12.189274
Hawaii                  12.106027
Nebraska                12.091383
South Dakota            11.638704
Wyoming                 10.186102
Alaska                   9.612409
Virgin Islands           7.410247
Guam                     6.616759
Name: wage_prem_25th, dtype: float64

In [68]:
wageprem75th =countyrent.groupby(by='STATE')['A_PCT75'].agg('median').sort_values(ascending=False)
state75th = dict()
for i in range(len(wageprem75th.index)):
  state75th[wageprem75th.index[i]] = wageprem75th.values[i]
countyrent['stateprem75th']= countyrent.apply(lambda x : wageprem75th[x['STATE']] if x['STATE'] in state75th else 0,axis=1)
countyrent['wage_prem_75th'] = countyrent['A_PCT75'] / countyrent['stateprem75th']
countyrent[countyrent['OCC_TITLE'].str.contains('Analysts')].groupby('STATE')['wage_prem_75th'].agg('sum').sort_values(ascending=False)

STATE
New York                18.036136
Alabama                 17.851951
North Carolina          17.680468
Texas                   16.920331
Florida                 16.811526
Virginia                16.743481
Colorado                16.387183
California              16.196350
Arizona                 16.082179
New Jersey              15.920975
Washington              15.840988
Arkansas                15.689449
Maryland                15.673555
Ohio                    15.666607
Missouri                15.480014
Tennessee               15.335276
Idaho                   15.297222
South Carolina          15.277395
Delaware                15.165553
New Hampshire           15.080679
Utah                    15.054683
New Mexico              15.001666
Mississippi             14.877157
District of Columbia    14.863105
Indiana                 14.839117
Kentucky                14.595829
Wisconsin               14.463930
Rhode Island            14.293773
Puerto Rico             14.242662
Illinois                14.099013
Pennsylvania            13.949941
Georgia                 13.857143
Michigan                13.810936
Iowa                    13.769332
Louisiana               13.732842
Vermont                 13.732350
Nevada                  13.666282
Minnesota               13.597075
Kansas                  13.545776
Oklahoma                13.509261
Connecticut             13.508869
Massachusetts           13.492075
Maine                   13.380276
Montana                 13.114637
Oregon                  12.940174
Nebraska                12.748415
North Dakota            12.677864
Hawaii                  12.593711
West Virginia           12.560061
South Dakota            12.221148
Alaska                  10.201654
Wyoming                  8.218486
Virgin Islands           7.172082
Guam                     6.395682
Name: wage_prem_75th, dtype: float64

In [69]:
wageprem90th =countyrent.groupby(by='STATE')['A_PCT90'].agg('median').sort_values(ascending=False)
state90th = dict()
for i in range(len(wageprem90th.index)):
  state90th[wageprem90th.index[i]] = wageprem90th.values[i]
countyrent['stateprem90th']= countyrent.apply(lambda x : wageprem90th[x['STATE']] if x['STATE'] in state90th else 0,axis=1)
countyrent['wage_prem_90th'] = countyrent['A_PCT90'] / countyrent['stateprem90th']
countyrent[countyrent['OCC_TITLE'].str.contains('Analysts')].groupby('STATE')['wage_prem_90th'].agg('sum').sort_values(ascending=False)

STATE
North Carolina          20.218920
Texas                   19.232517
Colorado                18.609956
Virginia                17.620674
Ohio                    17.463444
Arizona                 17.391405
New Jersey              17.291268
Missouri                17.234403
New Hampshire           16.933961
Arkansas                16.894321
Idaho                   16.738557
Delaware                16.730818
Utah                    16.726862
Tennessee               16.493498
Maryland                16.486088
Wisconsin               16.481575
Mississippi             16.433472
Alabama                 16.381372
Indiana                 16.142676
Rhode Island            15.929421
South Carolina          15.847571
California              15.511225
Florida                 15.510182
Illinois                15.435138
Vermont                 15.404951
Pennsylvania            15.176096
Connecticut             15.036055
Georgia                 14.998929
Louisiana               14.957437
New Mexico              14.900635
Michigan                14.888312
Massachusetts           14.808773
New York                14.794163
Puerto Rico             14.756341
District of Columbia    14.644038
Kansas                  14.324708
Iowa                    14.254606
Nevada                  14.246520
Maine                   14.100144
Minnesota               14.051191
Oklahoma                13.896108
Washington              13.830292
North Dakota            13.764317
Kentucky                13.743922
Montana                 13.689791
Oregon                  13.142993
South Dakota            12.830029
West Virginia           12.735317
Nebraska                12.721923
Hawaii                  12.371873
Alaska                  11.105470
Wyoming                  8.832149
Virgin Islands           7.617438
Guam                     6.165686
Name: wage_prem_90th, dtype: float64

In [0]:
#certain states are better at the entry level amount of money for analysts and other states are better at senior level pay for analysts

In [71]:
#sum of all the wage premiums
countyrent[['wage_prem_10th','wage_prem_25th','wage_premium','wage_prem_75th','wage_prem_90th','STATE','OCC_TITLE']]

       wage_prem_10th  ...                                          OCC_TITLE
0            0.678457  ...                                    All Occupations
1            1.830668  ...                             Management Occupations
2            2.992662  ...                                   Chief Executives
3            1.888241  ...                    General and Operations Managers
4            0.613735  ...                                        Legislators
...               ...  ...                                                ...
36892        0.885339  ...       Automotive and Watercraft Service Attendants
36893        1.021882  ...                  Transportation Workers, All Other
36894        0.926039  ...             Industrial Truck and Tractor Operators
36895        0.883151  ...  Laborers and Freight, Stock, and Material Move...
36896        0.882713  ...                        Packers and Packagers, Hand

[36897 rows x 7 columns]

In [0]:
#there is a all occupations wage percentiles which is lower in the 10th percentile relative to my wage premium average( of all job titles not weighted for all people)
# that is because a relatively few job titles must have a lot of workers who are in the bottom. Meaning since in my calculation each job title is equal weight
#the calculation is wrong because there should be a large weight added to those job titles making a small amount since they have a lot more jobs in that title
#the other end is similar meaning that

#there are columns that tally the management occupations that I need to delete to have the calculations right
#also there are zero values in chief executives for some reason?

In [75]:
countyrent[(countyrent['STATE']=='Alabama') & (countyrent['OCC_TITLE']=='Chief Executives')]

   Unnamed: 0  AREA  ST  ... wage_prem_75th stateprem90th wage_prem_90th
2           2     1  AL  ...            0.0         62380            0.0

[1 rows x 39 columns]

In [0]:
#chief executives make too much and has a zero value. I should not include them or I could extrapolate what those are given other jobs ratios between median and 90th
#if I do either the data would not be completely accurate.

In [83]:
countyrent[(countyrent['A_PCT90']==0) | (countyrent['A_PCT10']==0)]['OCC_TITLE'].value_counts()[:20]
#I could get rid of all of these jobs from the calculation but it is a lot of the jobs and a lot of the states
#these jobs either make too much money on the 90th percentile or they have no way to calculate them so its all blank
#I could use the hourly salary but that can be wrong since they jobs sometimes work different amounts of hours

Chief Executives                                                      53
Physicians and Surgeons, All Other                                    52
Family and General Practitioners                                      51
Anesthesiologists                                                     50
Surgeons                                                              50
Dentists, General                                                     50
Internists, General                                                   50
Psychiatrists                                                         48
Obstetricians and Gynecologists                                       48
Pediatricians, General                                                46
Musicians and Singers                                                 41
Nurse Anesthetists                                                    40
Personal Financial Advisors                                           36
Entertainers and Performers, Sports and Related Workers, All Other    35
Sales Managers                                                        32
Actors                                                                32
Podiatrists                                                           31
Orthodontists                                                         31
Health Specialties Teachers, Postsecondary                            30
General and Operations Managers                                       26
Name: OCC_TITLE, dtype: int64

In [86]:
countyrent[countyrent['H_MEDIAN']>0]['OCC_TITLE'].value_counts()
#the amount of jobs with at least 1 state where hourly median has a greater than 0 value - 771

Tellers                         54
Public Relations Specialists    54
Computer Systems Analysts       54
Pharmacists                     54
Postal Service Mail Carriers    54
                                ..
Model Makers, Wood               3
Prosthodontists                  2
Cooks, Private Household         1
Farm Labor Contractors           1
Locomotive Firers                1
Name: OCC_TITLE, Length: 771, dtype: int64

In [88]:
countyrent['OCC_TITLE'].value_counts()
#the amount of job titles in general - 831

Licensed Practical and Licensed Vocational Nurses    54
Compliance Officers                                  54
Public Relations Specialists                         54
Social and Community Service Managers                54
Driver/Sales Workers                                 54
                                                     ..
Fabric Menders, Except Garment                        3
Prosthodontists                                       2
Cooks, Private Household                              1
Locomotive Firers                                     1
Farm Labor Contractors                                1
Name: OCC_TITLE, Length: 831, dtype: int64

In [105]:
#there are 60 jobs that do not have hourly data - (total jobs 831 - jobs that have some hourly data 771) = 60
countyrent[countyrent['H_MEDIAN']==0]['OCC_TITLE'].value_counts()

Secondary School Teachers, Except Special and Career/Technical Education    54
Teachers and Instructors, All Other, Except Substitute Teachers             54
Elementary School Teachers, Except Special Education                        54
Teacher Assistants                                                          54
Education Administrators, Elementary and Secondary School                   54
                                                                            ..
Writers and Authors                                                          1
Morticians, Undertakers, and Funeral Directors                               1
Service Unit Operators, Oil, Gas, and Mining                                 1
Locksmiths and Safe Repairers                                                1
Geoscientists, Except Hydrologists and Geographers                           1
Name: OCC_TITLE, Length: 295, dtype: int64

In [0]:
jobswithsomedata =countyrent[countyrent['H_MEDIAN']>0]['OCC_TITLE'].value_counts()
alljobtitles =countyrent['OCC_TITLE'].value_counts()

In [110]:
main_list = list(set(alljobtitles.index) - set(jobswithsomedata.index))
main_list
#these jobs do not have any hourly, but I can see surgeon has hourly so I am doing something wrong
# I am subtracting jobs that have some data from all of them so the remainder should be jobs with no data for hourly median

['Sociology Teachers, Postsecondary',
 'Special Education Teachers, All Other',
 'Foreign Language and Literature Teachers, Postsecondary',
 'Art, Drama, and Music Teachers, Postsecondary',
 'Athletes and Sports Competitors',
 'Forestry and Conservation Science Teachers, Postsecondary',
 'Special Education Teachers, Preschool',
 'Physics Teachers, Postsecondary',
 'Mathematical Science Teachers, Postsecondary',
 'Career/Technical Education Teachers, Secondary School',
 'Social Work Teachers, Postsecondary',
 'Health Specialties Teachers, Postsecondary',
 'Law Teachers, Postsecondary',
 'Special Education Teachers, Secondary School',
 'Chemistry Teachers, Postsecondary',
 'Career/Technical Education Teachers, Middle School',
 'Kindergarten Teachers, Except Special Education',
 'Airline Pilots, Copilots, and Flight Engineers',
 'Postsecondary Teachers, All Other',
 'Special Education Teachers, Kindergarten and Elementary School',
 'Legislators',
 'Area, Ethnic, and Cultural Studies Teachers, Postsecondary',
 'Education Teachers, Postsecondary',
 'Architecture Teachers, Postsecondary',
 'Recreation and Fitness Studies Teachers, Postsecondary',
 'Special Education Teachers, Middle School',
 'Economics Teachers, Postsecondary',
 'English Language and Literature Teachers, Postsecondary',
 'Biological Science Teachers, Postsecondary',
 'Geography Teachers, Postsecondary',
 'Communications Teachers, Postsecondary',
 'Computer Science Teachers, Postsecondary',
 'Psychology Teachers, Postsecondary',
 'Education Administrators, Elementary and Secondary School',
 'Secondary School Teachers, Except Special and Career/Technical Education',
 'Agricultural Sciences Teachers, Postsecondary',
 'Social Sciences Teachers, Postsecondary, All Other',
 'Commercial Pilots',
 'Athletic Trainers',
 'Environmental Science Teachers, Postsecondary',
 'Philosophy and Religion Teachers, Postsecondary',
 'Teachers and Instructors, All Other, Except Substitute Teachers',
 'Business Teachers, Postsecondary',
 'Home Economics Teachers, Postsecondary',
 'Surgeons',
 'Umpires, Referees, and Other Sports Officials',
 'Teacher Assistants',
 'Graduate Teaching Assistants',
 'Flight Attendants',
 'Nursing Instructors and Teachers, Postsecondary',
 'Engineering Teachers, Postsecondary',
 'Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary',
 'Library Science Teachers, Postsecondary',
 'Elementary School Teachers, Except Special Education',
 'History Teachers, Postsecondary',
 'Coaches and Scouts',
 'Anthropology and Archeology Teachers, Postsecondary',
 'Criminal Justice and Law Enforcement Teachers, Postsecondary',
 'Middle School Teachers, Except Special and Career/Technical Education',
 'Political Science Teachers, Postsecondary']

In [0]:
#jobs with at least 1 state where hourly median is 0 but some jobs are not in all states
# i need to find how many states have each job
countyrent[countyrent['H_MEDIAN']==0]['OCC_TITLE'].value_counts().index.tolist()

In [104]:
countyrent['OCC_TITLE'].value_counts().loc['Surgeons']#there were only 50 states with surgeons

50

In [109]:
for i in main_list:
  print(countyrent['OCC_TITLE'].value_counts().loc[i] == countyrent[countyrent['H_MEDIAN']==0]['OCC_TITLE'].value_counts().loc[i])
#all true

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True

In [79]:
countyrent[(countyrent['A_PCT75']==0) & (countyrent['OCC_TITLE']=='Wellhead Pumpers')]

       Unnamed: 0  AREA  ST  ... wage_prem_75th stateprem90th wage_prem_90th
10411       10411    18  IN  ...            0.0         63080            0.0

[1 rows x 39 columns]

In [95]:
countyrent[countyrent['OCC_TITLE']=='Prosthodontists']
#some jobs are only in certain states

       Unnamed: 0  AREA  ST  ... wage_prem_75th stateprem90th wage_prem_90th
6364         6364    12  FL  ...            0.0         64085            0.0
32684       32684    51  VA  ...            0.0         66750            0.0

[2 rows x 39 columns]

In [117]:
countyrent[(countyrent['A_PCT75']==0) | (countyrent['A_PCT10']==0)]['OCC_TITLE'].value_counts().loc['Surgeons']

50

In [119]:
for i in countyrent['OCC_TITLE'].value_counts().index:
  try:
    print(countyrent['OCC_TITLE'].value_counts().loc[i],countyrent['OCC_TITLE'].value_counts().loc[i] - countyrent[(countyrent['A_PCT75']==0) | (countyrent['A_PCT10']==0)]['OCC_TITLE'].value_counts().loc[i],' ',i)
  except:
    continue

54 52   General and Operations Managers
54 52   Computer and Information Systems Managers
54 50   Sales Managers
54 53   Food Service Managers
54 53   Chefs and Head Cooks
54 53   Dining Room and Cafeteria Attendants and Bartender Helpers
54 52   Marketing Managers
54 53   Legal Occupations
54 52   Environmental Scientists and Specialists, Including Health
54 53   Security Guards
54 52   Office and Administrative Support Workers, All Other
54 52   Cement Masons and Concrete Finishers
54 53   Plumbers, Pipefitters, and Steamfitters
54 53   First-Line Supervisors of Housekeeping and Janitorial Workers
54 49   Lawyers
54 53   Computer Network Support Specialists
54 53   Insurance Sales Agents
54 52   Financial Managers
53 52   Advertising Sales Agents
53 2   Physicians and Surgeons, All Other
53 50   Cargo and Freight Agents
53 52   Financial Specialists, All Other
53 52   Lodging Managers
53 52   Computer Occupations, All Other
53 13   Chief Executives
53 52   Hazardous Materials Removal Workers
53 51   Tax Preparers
53 52   Legal Secretaries
53 51   Education Administrators, All Other
53 52   Logisticians
53 51   Architects, Except Landscape and Naval
53 52   Purchasing Managers
53 52   Financial Analysts
53 52   Order Clerks
53 52   Floral Designers
52 51   Veterinarians
52 51   Securities, Commodities, and Financial Services Sales Agents
52 50   Interior Designers
52 3   Family and General Practitioners
52 51   Software Developers, Applications
52 50   Optometrists
52 50   Photographers
52 50   Editors
52 50   Food Batchmakers
52 50   Computer Network Architects
52 51   Computer Programmers
52 50   Broadcast Technicians
52 50   Maintenance Workers, Machinery
52 50   Crane and Tower Operators
52 51   Refuse and Recyclable Material Collectors
52 51   Producers and Directors
52 51   Cardiovascular Technologists and Technicians
52 49   Personal Financial Advisors
52 51   Environmental Engineers
52 51   Substance Abuse, Behavioral Disorder, and Mental Health Counselors
52 50   Stationary Engineers and Boiler Operators
51 49   Weighers, Measurers, Checkers, and Samplers, Recordkeeping
51 50   Appraisers and Assessors of Real Estate
51 2   Anesthesiologists
51 49   Crossing Guards
51 49   Skincare Specialists
51 3   Internists, General
51 50   Writers and Authors
51 49   Mathematical Science Teachers, Postsecondary
51 48   Business Teachers, Postsecondary
51 49   Health Diagnosing and Treating Practitioners, All Other
51 50   Pharmacy Aides
51 50   Labor Relations Specialists
51 50   Protective Service Workers, All Other
51 49   Conservation Scientists
51 14   Dentists, General
51 50   Library Assistants, Clerical
51 50   New Accounts Clerks
51 50   Community Health Workers
50 49   Special Education Teachers, Middle School
50 43   Real Estate Brokers
50 46   Radio and Television Announcers
50 49   Art, Drama, and Music Teachers, Postsecondary
50 49   Sales Engineers
50 49   Mechanical Engineering Technicians
50 49   Computer Science Teachers, Postsecondary
50 48   Nursing Instructors and Teachers, Postsecondary
50 0   Surgeons
50 48   Morticians, Undertakers, and Funeral Directors
50 47   Medical Scientists, Except Epidemiologists
50 38   Health Specialties Teachers, Postsecondary
50 49   Electrical and Electronics Drafters
50 49   Chiropractors
50 49   Public Relations and Fundraising Managers
50 49   Education Teachers, Postsecondary
50 49   Healthcare Practitioners and Technical Workers, All Other
50 49   Occupational Health and Safety Technicians
50 49   Emergency Management Directors
49 48   Print Binding and Finishing Workers
49 16   Pediatricians, General
49 48   Locksmiths and Safe Repairers
49 3   Psychiatrists
49 48   English Language and Literature Teachers, Postsecondary
49 47   Power Plant Operators
49 48   Biological Science Teachers, Postsecondary
49 48   Electronic Home Entertainment Equipment Installers and Repairers
49 47   Psychology Teachers, Postsecondary
49 48   Statisticians
49 48   Credit Counselors
49 46   Environmental Engineering Technicians
49 48   Education Administrators, Postsecondary
49 48   Aircraft Mechanics and Service Technicians
49 48   Art Directors
49 48   Marriage and Family Therapists
49 48   Separating, Filtering, Clarifying, Precipitating, and Still Machine Setters, Operators, and Tenders
49 48   Geoscientists, Except Hydrologists and Geographers
48 47   Meter Readers, Utilities
48 46   Chemical Engineers
48 47   First-Line Supervisors of Farming, Fishing, and Forestry Workers
48 47   Extruding, Forming, Pressing, and Compacting Machine Setters, Operators, and Tenders
48 47   Industrial Engineering Technicians
48 46   Chemistry Teachers, Postsecondary
48 46   Transportation Inspectors
48 44   Camera Operators, Television, Video, and Motion Picture
48 1   Obstetricians and Gynecologists
48 45   Communications Teachers, Postsecondary
48 43   Engineering Teachers, Postsecondary
48 43   Natural Sciences Managers
48 47   Advertising and Promotions Managers
47 46   Special Education Teachers, All Other
47 46   Financial Clerks, All Other
47 36   Nurse Anesthetists
47 46   Landscape Architects
47 46   Pesticide Handlers, Sprayers, and Applicators, Vegetation
47 46   Automotive Glass Installers and Repairers
47 46   Personal Care and Service Workers, All Other
47 46   Computer-Controlled Machine Tool Operators, Metal and Plastic
46 45   Transportation Workers, All Other
46 45   Foreign Language and Literature Teachers, Postsecondary
46 45   Plant and System Operators, All Other
46 43   Private Detectives and Investigators
46 45   Compensation and Benefits Managers
45 44   Demonstrators and Product Promoters
45 43   Economics Teachers, Postsecondary
45 42   Political Science Teachers, Postsecondary
45 44   Atmospheric and Space Scientists
45 44   Sales and Related Workers, All Other
45 42   Audiologists
45 44   Orthotists and Prosthetists
45 44   Sociology Teachers, Postsecondary
45 41   Criminal Justice and Law Enforcement Teachers, Postsecondary
45 44   Plating and Coating Machine Setters, Operators, and Tenders, Metal and Plastic
44 43   Upholsterers
44 42   Umpires, Referees, and Other Sports Officials
44 43   Agricultural and Food Science Technicians
44 43   Ambulance Drivers and Attendants, Except Emergency Medical Technicians
44 42   Fire Inspectors and Investigators
44 42   Tailors, Dressmakers, and Custom Sewers
44 37   Legislators
43 38   Recreation and Fitness Studies Teachers, Postsecondary
43 41   Counselors, All Other
43 42   Rail-Track Laying and Maintenance Equipment Operators
43 39   Computer Hardware Engineers
43 41   Materials Engineers
43 42   Petroleum Pump System Operators, Refinery Operators, and Gaugers
43 42   Psychologists, All Other
43 42   Food Processing Workers, All Other
43 36   Film and Video Editors
42 41   Media and Communication Equipment Workers, All Other
42 41   Statistical Assistants
41 28   Podiatrists
41 40   Atmospheric, Earth, Marine, and Space Sciences Teachers, Postsecondary
41 40   Social Sciences Teachers, Postsecondary, All Other
41 40   Court Reporters
41 40   Plasterers and Stucco Masons
41 0   Musicians and Singers
41 40   Floor Layers, Except Carpet, Wood, and Hard Tiles
41 37   Judges, Magistrate Judges, and Magistrates
41 38   Music Directors and Composers
41 40   Railroad Conductors and Yardmasters
40 38   Milling and Planing Machine Setters, Operators, and Tenders, Metal and Plastic
40 39   Textile, Apparel, and Furnishings Workers, All Other
40 38   Chemical Plant and System Operators
40 36   Social Work Teachers, Postsecondary
40 38   Arbitrators, Mediators, and Conciliators
40 26   Airline Pilots, Copilots, and Flight Engineers
40 39   Graders and Sorters, Agricultural Products
39 38   Helpers--Extraction Workers
39 36   Graduate Teaching Assistants
39 37   Electro-Mechanical Technicians
39 37   Social Science Research Assistants
39 35   Fine Artists, Including Painters, Sculptors, and Illustrators
38 37   Avionics Technicians
38 37   Desktop Publishers
38 37   Electrical and Electronics Installers and Repairers, Transportation Equipment
38 35   Material Moving Workers, All Other
38 37   Anthropologists and Archeologists
38 36   Actuaries
38 36   Geological and Petroleum Technicians
38 36   Physicists
37 35   Survey Researchers
37 31   Funeral Service Managers
37 35   Biomedical Engineers
37 36   Set and Exhibit Designers
37 36   First-Line Supervisors of Gaming Workers
37 36   Cooling and Freezing Equipment Operators and Tenders
36 35   Parking Enforcement Workers
36 35   Aircraft Cargo Handling Supervisors
36 35   Cooks, All Other
36 34   Gaming Dealers
36 35   Hydrologists
36 35   Proofreaders and Copy Markers
36 34   Epidemiologists
35 34   Drilling and Boring Machine Tool Setters, Operators, and Tenders, Metal and Plastic
35 0   Entertainers and Performers, Sports and Related Workers, All Other
35 31   Captains, Mates, and Pilots of Water Vessels
35 34   Sailors and Marine Oilers
35 33   Engine and Other Machine Assemblers
35 30   Area, Ethnic, and Cultural Studies Teachers, Postsecondary
34 32   Railroad Brake, Signal, and Switch Operators
34 33   Judicial Law Clerks
34 31   Sound Engineering Technicians
34 31   Postsecondary Teachers, All Other
33 26   Law Teachers, Postsecondary
33 29   Biochemists and Biophysicists
33 28   Public Address System and Other Announcers
33 32   Materials Scientists
33 30   Life Scientists, All Other
33 31   Craft Artists
33 32   Traffic Technicians
33 32   Gaming Change Persons and Booth Cashiers
33 31   Farm and Home Management Advisors
32 16   Dentists, All Other Specialists
32 0   Actors
32 29   Agricultural Sciences Teachers, Postsecondary
32 30   Gaming Surveillance Officers and Gaming Investigators
32 27   Broadcast News Analysts
32 3   Orthodontists
32 30   Continuous Mining Machine Operators
32 30   Farmers, Ranchers, and Other Agricultural Managers
31 30   Shoe and Leather Workers and Repairers
31 30   Pump Operators, Except Wellhead Pumpers
31 26   Environmental Science Teachers, Postsecondary
31 19   Athletes and Sports Competitors
31 30   Anthropology and Archeology Teachers, Postsecondary
30 29   Tapers
30 25   Fashion Designers
29 24   Mining and Geological Engineers, Including Mining Safety Engineers
28 27   Genetic Counselors
28 26   Geography Teachers, Postsecondary
28 27   Agricultural Workers, All Other
28 24   Agents and Business Managers of Artists, Performers, and Athletes
28 23   Architecture Teachers, Postsecondary
27 26   Pourers and Casters, Metal
27 25   Rotary Drill Operators, Oil and Gas
27 26   Layout Workers, Metal and Plastic
27 26   Textile Knitting and Weaving Machine Setters, Operators, and Tenders
26 25   Telephone Operators
26 25   Door-to-Door Sales Workers, News and Street Vendors, and Related Workers
25 0   Dancers
25 23   Aerospace Engineering and Operations Technicians
25 24   Nuclear Engineers
25 24   Service Unit Operators, Oil, Gas, and Mining
25 24   Roustabouts, Oil and Gas
24 1   Oral and Maxillofacial Surgeons
24 21   Hoist and Winch Operators
24 17   Petroleum Engineers
23 21   Extraction Workers, All Other
22 21   Gaming Managers
22 21   Ship Engineers
22 21   Choreographers
21 17   Pile-Driver Operators
21 19   Flight Attendants
20 19   Wellhead Pumpers
19 18   Communications Equipment Operators, All Other
19 16   Forestry and Conservation Science Teachers, Postsecondary
19 18   Aircraft Structure, Surfaces, Rigging, and Systems Assemblers
18 17   Mine Cutting and Channeling Machine Operators
18 17   Miscellaneous Mathematical Science Occupations
18 17   Watch Repairers
17 15   Marine Engineers and Naval Architects
16 15   Mathematicians
16 15   Home Economics Teachers, Postsecondary
16 15   Mining Machine Operators, All Other
16 15   Nuclear Technicians
15 14   Models
11 9   Agricultural Engineers
10 9   Transit and Railroad Police
9 7   Radio Operators
6 4   Timing Device Assemblers and Adjusters
4 3   Model Makers, Wood
2 0   Prosthodontists